import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';

export default [
  {
    files: ['src/**/*.{ts,tsx}'],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        project: './tsconfig.json',
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      '@typescript-eslint': tseslint.plugin,
      'react-hooks': reactHooks,
    },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'error',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-floating-promises': ['warn', { ignoreVoid: true, ignoreIIFE: true }],
      '@typescript-eslint/no-misused-promises': [
        'warn',
        {
          checksVoidReturn: {
            arguments: false,
            attributes: false,
          },
        },
      ],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
  {
    files: [
      'src/annotation/**/*.{ts,tsx}',
      'src/app/**/*.{ts,tsx}',
      'src/collaboration/**/*.{ts,tsx}',
      'src/config/**/*.{ts,tsx}',
      'src/contexts/**/*.{ts,tsx}',
      'src/db/**/*.{ts,tsx}',
      'src/extensions/**/*.{ts,tsx}',
      'src/i18n/**/*.{ts,tsx}',
      'src/integrations/**/*.{ts,tsx}',
      'src/observability/**/*.{ts,tsx}',
      'src/perf/**/*.{ts,tsx}',
      'src/test/**/*.{ts,tsx}',
      'src/types/**/*.{ts,tsx}',
      'src/utils/**/*.{ts,tsx}',
      'src/workers/**/*.{ts,tsx}',
    ],
    rules: {
      '@typescript-eslint/strict-boolean-expressions': [
        'warn',
        {
          allowString: false,
          allowNumber: false,
          allowNullableObject: true,
        },
      ],
    },
  },
  {
    files: [
      'src/pages/OrthographyManagerPage.test.tsx',
      'src/pages/StructuralProfileWorkspacePage.test.tsx',
      'src/pages/transcriptionAcousticSummary.ts',
      'src/pages/transcriptionAiSelectionResolver.ts',
      'src/pages/transcriptionAssistantContextValue.ts',
      'src/pages/TranscriptionPage.AnalysisRuntime.tsx',
      'src/pages/TranscriptionPage.BatchOps.tsx',
      'src/pages/TranscriptionPage.helpers.ts',
      'src/pages/TranscriptionPage.ReadyWorkspaceLayout.tsx',
      'src/pages/transcriptionReadyWorkspaceMediaInputPropsBuilder.ts',
      'src/pages/transcriptionReadyWorkspaceOrchestratorInput.ts',
      'src/pages/transcriptionSelectionContextResolver.ts',
      'src/pages/transcriptionSelectionOwnerResolver.ts',
      'src/pages/transcriptionSelectionSnapshot.test.ts',
      'src/pages/TranscriptionTimelineWorkspaceHost.test.tsx',
      'src/pages/transcriptionToolbarProps.ts',
      'src/pages/transcriptionUnitTargetResolver.ts',
      'src/pages/useBatchOperationController.test.tsx',
      'src/pages/useBatchOperationController.ts',
      'src/pages/useReadyWorkspaceLayoutDerivations.ts',
      'src/pages/useReadyWorkspaceSegmentRangeClamp.ts',
      'src/pages/useReadyWorkspaceSegmentScope.ts',
      'src/pages/useReadyWorkspaceTimelineSyncController.ts',
      'src/pages/useTranscriptionAcousticPanelState.ts',
      'src/pages/useTranscriptionAiController.test.tsx',
      'src/pages/useTranscriptionAssistantController.test.tsx',
      'src/pages/useTranscriptionSegmentMutationController.test.tsx',
      'src/pages/useTranscriptionSelectionContextController.test.tsx',
      'src/pages/useTranscriptionTimelineContentViewModel.ts',
      'src/pages/useTranscriptionTimelineController.test.tsx',
      'src/pages/useTranscriptionTimelineInteractionController.test.tsx',
      'src/pages/useTranscriptionWorkspaceLayoutController.ts',
      'src/pages/useWaveformAcousticOverlay.ts',
      'src/pages/useWaveformViewportSizing.ts',
      'src/pages/voiceDictationFlow.ts',
      'src/pages/waveformAcousticOverlay.utils.ts',
      'src/pages/waveformRuntimeStorage.ts',
      'src/pages/HomePage.tsx',
      'src/pages/LanguageMetadataWorkspacePage.test.tsx',
      'src/pages/timelineUnitViewUnitHelpers.ts',
      'src/pages/TranscriptionPage.PdfRuntime.tsx',
      'src/pages/TranscriptionPage.ReadyWorkspace.runtime.ts',
      'src/pages/transcriptionReadyWorkspaceHistoryControlsBuilder.ts',
      'src/pages/transcriptionReadyWorkspacePropsBuilders.ts',
      'src/pages/transcriptionReadyWorkspaceStagePropsInputBuilder.ts',
      'src/pages/transcriptionTimelineTopProps.ts',
      'src/pages/useTrackEntityPersistenceController.ts',
      'src/pages/useTranscriptionAiAcousticBatchRanges.ts',
      'src/pages/useTranscriptionAiAcousticRuntime.ts',
      'src/pages/useTranscriptionAiController.segmentTargets.ts',
      'src/pages/useTranscriptionSegmentBridgeController.ts',
      'src/pages/useTranscriptionSpeakerController.ts',
      'src/pages/useWaveformSignalOverlays.ts',
      'src/pages/languageMetadataWorkspace.country.ts',
      'src/pages/orthographyManager.shared.ts',
      'src/pages/transcriptionAiReadModelAccessors.ts',
      'src/pages/transcriptionAiSelectionResolver.test.ts',
      'src/pages/TranscriptionPage.ChatWindow.tsx',
      'src/pages/TranscriptionPage.ToastController.tsx',
      'src/pages/TranscriptionPage.Toolbar.tsx',
      'src/pages/transcriptionWorkspaceLayoutControllerPrefs.ts',
      'src/pages/useReadyWorkspaceRenderController.ts',
      'src/pages/useSpeakerActionRoutingController.test.tsx',
      'src/pages/useTrackDisplayController.test.tsx',
      'src/pages/useTranscriptionAssistantController.ts',
      'src/pages/useTranscriptionSegmentBatchMerge.ts',
    ],
    rules: {
      '@typescript-eslint/strict-boolean-expressions': [
        'warn',
        {
          allowString: false,
          allowNumber: false,
          allowNullableObject: true,
        },
      ],
    },
  },
  {
    ignores: ['dist/', 'node_modules/', 'src/data/generated/'],
  },
];
