/**
 * CSS contract guards (`src/styles/**`): required literals + forbidden zones.
 * Phase 0.4 — split from `architecture-guard.config.mjs`.
 */
export const architectureGuardCssFileRules = [
  {
    file: 'src/styles/foundation/dialog-shell.css',
    requiredLiterals: [
      '.dialog-card {',
      '.dialog-header {',
      '.dialog-body {',
      '.dialog-footer {',
      '.dialog-card-compact {',
    ],
  },
  {
    file: 'src/styles/foundation/panel-primitives.css',
    requiredLiterals: [
      '.panel-section {',
      '.panel-button {',
      '.panel-input {',
      '.panel-chip {',
    ],
  },
  {
    file: 'src/styles/foundation/control-primitives.css',
    requiredLiterals: [
      '.select-caret {',
      '.input {',
      '.btn {',
      '.icon-btn {',
    ],
  },
  {
    file: 'src/styles/pages/transcription-layout.css',
    requiredLiterals: [
      '.app-shell-transcription {',
      '.app-main-transcription {',
      '.transcription-screen {',
      '.transcription-workspace {',
      '.transcription-list-panel {',
      '.transcription-side-pane {',
      '.focus-mode-badge {',
    ],
  },
  {
    file: 'src/styles/pages/transcription-toolbar.css',
    requiredLiterals: [
      '.transcription-wave-toolbar {',
      '.transcription-wave-toolbar-right {',
      '.app-left-rail-bottom-slot .transcription-wave-toolbar-right-portaled {',
      '.transcription-ai-observer-status {',
      '.transcription-ai-observer-status-bar {',
      '.transcription-ai-observer-stage-label {',
    ],
  },
  {
    file: 'src/styles/pages/transcription-waveform-shell.css',
    requiredLiterals: ['.transcription-waveform {'],
  },
  {
    file: 'src/styles/pages/transcription-timeline.css',
    requiredLiterals: [
      "@import './timeline/timeline-segment-narrow.css';",
      '.timeline-scroll {',
      '.timeline-content {',
      '.timeline-lane {',
      '.timeline-annotation {',
      '.timeline-text-item {',
      '.timeline-translation-audio-controls {',
      '.timeline-annotation-subtrack {',
      '.timeline-lane-focused {',
      '.timeline-lane-label {',
      '.lane-label-resize-handle {',
      '.lane-link-stack {',
      '.waveform-overview-bar {',
      '.timeline-lane-resize-handle {',
      '.timeline-lane-row-dragging {',
    ],
  },
  {
    file: 'src/styles/pages/ai-sidebar-shell.css',
    requiredLiterals: [
      '.transcription-hub-sidebar {',
      '.transcription-ai-panel {',
      '.transcription-ai-panel-toggle {',
      '.transcription-ai-panel-resizer {',
    ],
  },
  {
    file: 'src/styles/pages/app-shell-layout.css',
    requiredLiterals: [
      '.app-shell {',
      '.app-shell-body {',
      '.app-main {',
      '.app-side-pane {',
    ],
  },
  {
    file: 'src/styles/pages/feature-availability.css',
    requiredLiterals: [
      '.app-side-pane-feature-stack {',
      '.app-side-pane-feature-badge {',
      '.feature-availability-panel {',
      '.feature-availability-link {',
    ],
  },
  {
    file: 'src/styles/panels/shortcuts-panel.css',
    requiredLiterals: [
      '.pnl-shortcuts-panel {',
      '.shortcuts-panel-header {',
      '.shortcuts-panel-body {',
      '.shortcuts-panel-table {',
    ],
  },
  {
    file: 'src/styles/panels/ai-chat-thread.css',
    requiredLiterals: [
      '.ai-chat-message-viewport {',
      '.ai-chat-message-canvas {',
      '.ai-chat-message-surface {',
      '.ai-chat-message-actions {',
    ],
  },
  {
    file: 'src/styles/panels/left-rail-project-hub.css',
    requiredLiterals: [
      '.left-rail-project-hub-root {',
      '.left-rail-project-import-dialog {',
      '.left-rail-project-import-table {',
      '.left-rail-project-import-actions {',
    ],
  },
  {
    file: 'src/styles/panels/undo-history.css',
    requiredLiterals: [
      '.transcription-undo-chip {',
      '.transcription-undo-history {',
      '.transcription-undo-history-item {',
      '.transcription-undo-history-redo {',
    ],
  },
  {
    file: 'src/styles/global.css',
    forbiddenRegexes: [
      /^\.select-caret(?=[:\s,{])/m,
      /^\.input(?=[:\s,{])/m,
      /^\.textarea(?=[:\s,{])/m,
      /^\.btn(?=[:\s,{])/m,
      /^\.btn-ghost(?=[:\s,{])/m,
      /^\.btn-danger(?=[:\s,{])/m,
      /^\.icon-btn(?=[:\s,{])/m,
      /^\.app-shell\s*\{/m,
      /^\.app-shell-body\s*\{/m,
      /^\.app-main\s*\{/m,
      /^\.app-left-rail\s*\{/m,
      /^\.app-left-rail-group\s*\{/m,
      /^\.app-left-rail-bottom-slot\s*\{/m,
      /^\.app-side-pane\s*\{/m,
      /^\.app-side-pane-transcription\s*\{/m,
      /^\.app-shell-side-pane-collapsed\b/m,
      /^\.app-side-pane-collapsed\b/m,
      /^\.app-side-pane-collapse-toggle\b/m,
      /^\.app-side-pane-handle-cluster\b/m,
      /^\.app-side-pane-hover-zone\s*\{/m,
      /^\.app-side-pane-resizer\b/m,
      /^\.app-side-pane-header\s*\{/m,
      /^\.app-side-pane-title\s*\{/m,
      /^\.app-side-pane-subtitle\s*\{/m,
      /^\.app-side-pane-body\s*\{/m,
      /^\.app-side-pane-body-slot\s*\{/m,
      /^\.app-side-pane-empty-state\b/m,
      /^\.app-main-transcription\b/m,
      /^\.app-side-pane-feature-stack/m,
      /^\.app-side-pane-feature-nav/m,
      /^\.app-side-pane-feature-badge/m,
      /^\.app-side-pane-feature-summary/m,
      /^\.app-side-pane-feature-item/m,
      /^\.app-side-pane-feature-link/m,
      /^\.feature-availability-panel/m,
      /^\.feature-availability-badge/m,
      /^\.feature-availability-summary/m,
      /^\.feature-availability-block/m,
      /^\.feature-availability-label/m,
      /^\.feature-availability-list/m,
      /^\.feature-availability-actions/m,
      /^\.feature-availability-link/m,
    ],
  },
  {
    file: 'src/styles/pages/transcription-waveform.css',
    forbiddenRegexes: [
      /^\.dialog-overlay/m,
      /^\.dialog-card\s*\{/m,
      /^\.dialog-header\s*\{/m,
      /^\.dialog-body\s*\{/m,
      /^\.dialog-footer\s*\{/m,
      /^\.panel-organization-surface\s*\{/m,
      /^\.side-pane-action-modal/m,
      /^\.transcription-side-pane-speaker-panel/m,
      /^\.speaker-action-dialog/m,
      /^\.speaker-management-panel-card/m,
      /^\.speaker-management-dialog-actions/m,
      /^\.layer-action-dialog/m,
      /^\.layer-manager__/m,
      /^\.batch-operation/m,
      /^\.pdf-viewer-panel/m,
      /^\.transcription-screen\s*\{/m,
      /^\.app-shell-transcription\s*\{/m,
      /^\.app-shell-transcription \.app-main-transcription\s*\{/m,
      /^\.app-main-transcription \.transcription-screen\s*\{/m,
      /^\.transcription-workspace\s*\{/m,
      /^\.transcription-list-panel\s*\{/m,
      /^\.transcription-list-main\s*\{/m,
      /^\.transcription-side-pane\s*\{/m,
      /^\.transcription-side-pane::after/m,
      /^\.transcription-waveform\s*\{/m,
      /^\.transcription-wave-toolbar/m,
      /^\.transcription-toolbar-/m,
      /^\.app-left-rail-bottom-slot \.transcription-wave-toolbar-right-portaled/m,
      /^\.transcription-ai-observer-/m,
      /^\.timeline-scroll\s*\{/m,
      /^\.timeline-content\s*\{/m,
      /^\.timeline-lasso-rect\s*\{/m,
      /^\.timeline-lane\s*\{/m,
      /^\.timeline-annotation-subtrack/m,
      /^\.timeline-lane-(translation|focused|collapsed|overlap-hint|flash|header)/m,
      /^\.timeline-lane-label\s*\{/m,
      /^\.lane-label-resize-handle\s*\{/m,
      /^\.transcription-list-main-lane-header-collapsed \.timeline-lane-label/m,
      /^\.timeline-lane-resize-handle/m,
      /^\.timeline-lane-row-dragging\s*\{/m,
      /^\.timeline-lane-boundary-highlight-top::before/m,
      /^\.timeline-lane-bundle-target\s*\{/m,
      /^\.timeline-annotation/m,
      /^\.timeline-content-text-only\s*\{/m,
      /^\.timeline-text-item/m,
      /^\.timeline-text-input\s*\{/m,
      /^@keyframes timeline-status-pulse/m,
      /^\.timeline-translation-audio-/m,
      /^\.timeline-empty-/m,
      /^\.timeline-resize-tooltip\s*\{/m,
      /^\.waveform-area-resizing\s*\{/m,
      /^\.transcription-waveform-resize-handle\s*\{/m,
      /^\.ai-chat-message-viewport/m,
      /^\.ai-chat-message-canvas/m,
      /^\.ai-chat-message-surface/m,
      /^\.ai-chat-message-actions/m,
      /^\.ai-chat-message-action-btn/m,
      /^\.ai-citation-marker/m,
      /^\.transcription-analysis-panel/m,
      /^\.transcription-ai-stats-panel/m,
      /^\.left-rail-project-hub-root/m,
      /^\.left-rail-project-import-dialog/m,
      /^\.left-rail-project-import-table/m,
      /^\.transcription-undo-chip/m,
      /^\.transcription-undo-history/m,
    ],
  },
  {
    file: 'src/styles/ai-hub.css',
    forbiddenRegexes: [
      /^\.dialog-card\s*\{/m,
      /^\.note-panel/m,
      /^\.note-popover/m,
      /^\.ai-chat-replay-panel/m,
      /^\.ai-chat-prompt-lab-panel-content/m,
      /^\.ai-chat-prompt-lab-template-row/m,
      /^\.ai-chat-prompt-lab-item-title/m,
      /^\.ai-chat-prompt-lab-input/m,
      /^\.ai-chat-prompt-lab-textarea/m,
      /^\.ai-chat-prompt-lab-token-row/m,
      /^\.ai-chat-prompt-lab-action-row/m,
      /^\.transcription-hub-sidebar(\s|\{|-)/m,
      /^\.transcription-ai-tab-badge/m,
      /^\.transcription-hub-assistant-panel\s*\{/m,
      /^\.transcription-ai-panel\s*\{/m,
      /^\.transcription-ai-panel::before/m,
      /^\.transcription-ai-panel-toggle\s*\{/m,
      /^\.transcription-ai-panel-resizer\s*\{/m,
      /^\.transcription-ai-panel-handle-cluster\s*\{/m,
      /^\.transcription-undo-chip/m,
      /^\.transcription-undo-chip-label/m,
    ],
  },
];
