/** The 17 Universal Dependencies POS tags. Custom labels stay allowed and export as XPOS. */
export const UD_POS_TAGS = [
  'ADJ',
  'ADP',
  'ADV',
  'AUX',
  'CCONJ',
  'DET',
  'INTJ',
  'NOUN',
  'NUM',
  'PART',
  'PRON',
  'PROPN',
  'PUNCT',
  'SCONJ',
  'SYM',
  'VERB',
  'X',
] as const;
