/**
 * Re-exports Dexie document types for page modules (M3: `src/pages/*` must not import `../db` directly).
 */

export type {
  CustomFieldDefinitionDocType,
  CustomFieldValueType,
  LanguageCatalogHistoryDocType,
  LayerDisplaySettings,
  LayerDocType,
  LayerLinkDocType,
  LayerSegmentViewDocType,
  LayerUnitContentDocType,
  LayerUnitContentViewDocType,
  LayerUnitDocType,
  LexemeDocType,
  LexemeEntryDoc,
  LexemeResourceDoc,
  DmlexRelation,
  NoteCategory,
  TierDefinitionDocType,
  TokenLexemeLinkDocType,
  TokenLexemeLinkRole,
  LexemeAssetDocType,
  LexemeAssetLinkDocType,
  MediaItemDocType,
  MultiLangString,
  OrthographyDocType,
  ActorType,
  CreationMethod,
  ProvenanceEnvelope,
  ReviewStatus,
  SpeakerDocType,
  UnitMorphemeDocType,
  UnitRelationDocType,
  UnitTokenDocType,
  TextDocType,
  UserNoteDocType,
} from '../db';
