/**
 * AI 聊天领域类型 — 从 chatDomain.types 统一导出。
 */
export type {
  AiSessionMemory,
  AiSessionMemoryPreferences,
  AiSessionMemoryProjectFact,
  AiSessionMemorySummaryEntry,
  AiSessionMemorySummaryQualityWarning,
  AiPromptContext,
  AiSystemPersonaKey,
  AiShortTermContext,
  AiLongTermContext,
  AiChatToolCall,
  AiChatToolResult,
  AiChatToolName,
  AiRecommendationEvent,
  AiRecommendationSource,
  AiRecommendationEventType,
  AiRecommendationTelemetry,
  AiInteractionMetrics,
  AiTaskSession,
  AiClarifyCandidate,
  AiAdaptiveInputProfile,
  AiAdaptiveIntent,
  AiAdaptiveResponseStyle,
  ToolAuditContext,
  ToolPlannerClarifyReason,
  PendingAiToolCall,
  PreviewContract,
  AiToolRiskCheckResult,
  AiContextDebugSnapshot,
  UiChatMessage,
  AiConnectionTestStatus,
  AiToolDecisionMode,
  UseAiChatOptions,
} from './chatDomain.types';
