import type { Locale } from '../i18n';

import type { UseReadyWorkspaceTimelineAssistantPlaybackPhaseParams } from './useReadyWorkspaceTimelineAssistantPlaybackPhase';

type TranscriptionDataReturn = ReturnType<
  typeof import('../hooks/useTranscriptionData').useTranscriptionData
>;
type DomainShellReturn = ReturnType<
  typeof import('./useReadyWorkspaceDomainShellPhase').useReadyWorkspaceDomainShellPhase
>;
type PreBootstrapReturn = ReturnType<
  typeof import('./useReadyWorkspacePreBootstrapChromePhase').useReadyWorkspacePreBootstrapChromePhase
>;
type BootstrapReturn = ReturnType<
  typeof import('./useReadyWorkspaceReadyPhaseBootstrap').useReadyWorkspaceReadyPhaseBootstrap
>;
type WaveformBridgeReturn = ReturnType<
  typeof import('./useReadyWorkspaceWaveformBridgePhase').useReadyWorkspaceWaveformBridgePhase
>;
type SelectionAiReturn = ReturnType<
  typeof import('./useReadyWorkspaceSelectionAndAiPrepPhase').useReadyWorkspaceSelectionAndAiPrepPhase
>;

export interface BuildReadyWorkspaceTimelineAssistantPlaybackPhaseDeps {
  data: TranscriptionDataReturn;
  domainShell: DomainShellReturn;
  locale: Locale;
  tfB: (key: string, opts?: Record<string, unknown>) => string;
  pre: PreBootstrapReturn;
  bootstrap: BootstrapReturn;
  waveform: WaveformBridgeReturn;
  selectionAi: SelectionAiReturn;
}

export function buildReadyWorkspaceTimelineAssistantPlaybackPhaseParams(
  deps: BuildReadyWorkspaceTimelineAssistantPlaybackPhaseDeps,
): UseReadyWorkspaceTimelineAssistantPlaybackPhaseParams {
  const { data, domainShell, locale, tfB, pre, bootstrap, waveform, selectionAi } = deps;
  const {
    state,
    units,
    translationLayers,
    selectedTimelineUnit,
    selectedUnitIds,
    selectedMediaUrl,
    unitsOnCurrentMedia,
    anchors,
    layers,
    translations,
    defaultTranscriptionLayerId,
    loadSnapshot,
    setSaveState,
    saveUnitText,
    saveUnitLayerText,
    saveVoiceTranslation,
    selectUnit,
    addMediaItem,
    setSelectedLayerId,
    aiConfidenceAvg,
    setUnits,
    pushUndo,
    mediaItems: mediaItemsFromData,
  } = data;

  const {
    activeTimelineUnitId,
    segmentScopeMediaId,
    segmentsByLayer,
    reloadSegments,
    activeLayerIdForEdits,
    resolveSegmentRoutingForLayer,
    selectedTimelineOwnerUnit,
    selectedTimelineUnitForTime,
    selectedTimelineMedia,
    activeTextId,
    activeTextTimelineMode,
    getActiveTextId,
    setActiveTextId,
    setShowAudioImport,
    openPdfPreviewRequest,
    setFocusedLayerRowId,
    setFlashLayerRowId,
    nextUnitIdForVoiceDictation,
    segmentScopeMediaItem,
    saveSegmentContentForLayer,
  } = domainShell;

  const {
    selectionSnapshot,
    setAiSidebarError,
    deferredAiRuntime,
    setAiPanelContext,
    selectedAiWarning,
    lexemeMatches,
    selectedTranslationGapCount,
    vadCacheStatus,
    aiCurrentTask,
    aiVisibleCards,
    aiPanelMode,
    setAiPanelMode,
    acousticConfigOverride,
    acousticProviderPreference,
    handleJumpToTranslationGap,
    handlePinInspector,
    handleClearPinnedInspector,
    handleSelectHotspot,
    handleChangeAcousticConfig,
    handleResetAcousticConfig,
    handleChangeAcousticProvider,
    handleRefreshAcousticProviderState,
    acousticInspector,
    pinnedInspector,
    selectedHotspotTimeSec,
  } = selectionAi;

  const {
    setSubSelectionRange,
    setDragPreview,
    zoomToPercent,
    zoomToUnit,
    player,
    waveformTimelineItems,
    subSelectDragRef,
    waveCanvasRef,
    selectedWaveformRegionId,
    timelineViewportProjection,
    creatingSegmentRef,
    markingModeRef,
    waveformAreaRef,
    waveformInteractionHandlerRefs,
    subSelectionRange,
    segMarkStart,
    setSegMarkStart,
    segmentLoopPlayback,
    setSegmentLoopPlayback,
    skipSeekForIdRef,
  } = waveform;

  const {
    runSplitAtTime,
    createUnitFromSelectionRouted,
    runDeleteSelection,
    runMergePrev,
    runMergeNext,
    runSelectBefore,
    runSelectAfter,
  } = bootstrap;

  const {
    setCtxMenu,
    snapEnabled,
    setNotePopover,
    executeActionRef,
    openSearchRef,
    seekToTimeRef,
    splitAtTimeRef,
    zoomToSegmentRef,
    verticalViewActive,
  } = pre;

  return {
    timelineSync: {
      data,
      setSubSelectionRange,
      setDragPreview,
      zoomToPercent,
      zoomToUnit,
      setCtxMenu,
      reloadSegments,
      locale,
      manualSelectTsRef: pre.manualSelectTsRef,
      player,
      activeTimelineUnitId,
      waveformTimelineItems,
      activeLayerIdForEdits,
      useSegmentWaveformRegions: waveform.useSegmentWaveformRegions,
      selectedTimelineUnit,
      subSelectDragRef,
      waveCanvasRef,
      resolveSegmentRoutingForLayer,
      segmentsByLayer,
      unitsOnCurrentMedia,
      selectedUnitIds,
      selectedWaveformRegionId,
      snapEnabled,
      creatingSegmentRef,
      markingModeRef,
      setNotePopover,
      setAiSidebarError,
      openPdfPreviewRequest,
      runSplitAtTime,
      createUnitFromSelectionRouted,
      setSelectedLayerId,
      setFocusedLayerRowId,
      setFlashLayerRowId,
      selectSegment: data.selectSegment,
      timelineViewportProjection,
    },
    assistant: {
      state,
      unitsLength: units.length,
      translationLayersLength: translationLayers.length,
      aiConfidenceAvg,
      selectedPrimaryUnitView: selectionSnapshot.selectedUnit,
      selectedTimelineOwnerUnit: selectedTimelineOwnerUnit ?? null,
      selectedTimelineRowMeta: domainShell.selectedTimelineRowMeta,
      selectedAiWarning,
      lexemeMatches,
      handleOpenWordNote: pre.handleOpenWordNote,
      handleOpenMorphemeNote: pre.handleOpenMorphemeNote,
      handleUpdateTokenPos: pre.handleUpdateTokenPos,
      handleBatchUpdateTokenPosByForm: pre.handleBatchUpdateTokenPosByForm,
      aiPanelMode,
      setAiPanelMode,
      aiCurrentTask,
      aiVisibleCards,
      vadCacheStatus,
      acousticRuntimeStatus: deferredAiRuntime.acousticRuntimeStatus,
      acousticSummary: deferredAiRuntime.acousticSummary,
      acousticInspector,
      pinnedInspector,
      selectedHotspotTimeSec,
      acousticDetail: deferredAiRuntime.acousticDetail,
      acousticDetailFullMedia: deferredAiRuntime.acousticDetailFullMedia,
      acousticBatchDetails: deferredAiRuntime.acousticBatchDetails,
      acousticBatchSelectionCount: deferredAiRuntime.acousticBatchSelectionCount,
      acousticBatchDroppedSelectionRanges: deferredAiRuntime.acousticBatchDroppedSelectionRanges,
      acousticCalibrationStatus: deferredAiRuntime.acousticCalibrationStatus,
      acousticConfigOverride,
      acousticProviderPreference,
      acousticProviderState: deferredAiRuntime.acousticProviderState,
      selectedTranslationGapCount,
      handleJumpToTranslationGap,
      handleJumpToAcousticHotspot: deferredAiRuntime.onJumpToAcousticHotspot,
      handlePinInspector,
      handleClearPinnedInspector,
      handleSelectHotspot,
      handleChangeAcousticConfig,
      handleResetAcousticConfig,
      handleChangeAcousticProvider,
      handleRefreshAcousticProviderState,
      setAiPanelContext,
      selectedTimelineUnit,
      saveSegmentContentForLayer,
      selectedLayerId: data.selectedLayerId,
      ...(defaultTranscriptionLayerId !== undefined ? { defaultTranscriptionLayerId } : {}),
      translationLayers,
      layers,
      layerLinks: data.layerLinks,
      unitsOnCurrentMedia,
      getUnitTextForLayer: data.getUnitTextForLayer,
      saveUnitText,
      saveUnitLayerText,
      setSaveState,
      ...(nextUnitIdForVoiceDictation ? { nextUnitIdForVoiceDictation } : {}),
      selectUnit,
      aiChatEnabled: deferredAiRuntime.aiChat.enabled,
      aiChatSettings: deferredAiRuntime.aiChat.settings,
      pushUndo,
      setUnits,
    },
    playback: {
      data,
      player,
      waveformBridge: {
        subSelectionRange,
        setSubSelectionRange,
        segMarkStart,
        setSegMarkStart,
        segmentLoopPlayback,
        setSegmentLoopPlayback,
        markingModeRef,
        skipSeekForIdRef,
        creatingSegmentRef,
        manualSelectTsRef: pre.manualSelectTsRef,
        waveformAreaRef,
        waveformInteractionHandlerRefs,
        openSearchFromRequest: domainShell.openSearchFromRequest,
      },
      selectedTimelineOwnerUnit,
      selectedTimelineUnitForTime,
      selectedTimelineUnit,
      selectedUnitIds,
      selectedMediaUrl,
      createUnitFromSelectionRouted,
      runDeleteSelection,
      runMergePrev,
      runMergeNext,
      runSplitAtTime,
      runSelectBefore,
      runSelectAfter,
      timelineUnitViewIndex: pre.timelineUnitViewIndex,
      activeTextTimelineMode,
      zoomPxPerSec: timelineViewportProjection.zoomPxPerSec,
      fitPxPerSec: timelineViewportProjection.fitPxPerSec,
      verticalViewActive,
      executeActionRef,
      openSearchRef,
      seekToTimeRef,
      splitAtTimeRef,
      zoomToSegmentRef,
      activeLayerIdForEdits,
      documentSpanSecFromBridgeRef: pre.documentSpanSecFromBridgeRef,
    },
    audioCaptureBuild: {
      recordingInput: {
        saveVoiceTranslation,
        setSaveState,
        selectUnit,
        manualSelectTsRef: pre.manualSelectTsRef,
      },
      importExportInput: {
        activeTextId,
        getActiveTextId,
        segmentScopeMediaId,
        unitsOnCurrentMedia,
        anchors,
        layers,
        translations,
        defaultTranscriptionLayerId,
        loadSnapshot,
        setSaveState,
      },
      selectedTimelineMedia,
      segmentScopeMediaItem,
      projectMediaInput: {
        activeTextId,
        mediaItems: mediaItemsFromData,
        getActiveTextId,
        setActiveTextId,
        setShowAudioImport,
        addMediaItem,
        setSaveState,
        unitsOnCurrentMedia,
        createUnitFromSelectionRouted,
        loadSnapshot,
        selectTimelineUnit: data.selectTimelineUnit,
        locale,
        tfB,
        transcriptionLayers: data.transcriptionLayers,
        translationLayers,
        translationTextByLayer: data.translationTextByLayer,
        getUnitTextForLayer: data.getUnitTextForLayer,
      },
      selectedMediaUrl,
    },
  };
}
