/**
 * Phase C1: deep module for ReadyWorkspace surface props assembly (side pane / waveform / overlays /
 * layout / stage). Public entry remains `useReadyWorkspaceSurfaceProps` in `useReadyWorkspaceSurfaceProps.tsx`.
 */

import { hasSupabaseBrowserClientConfig } from '../integrations/supabase/client';
import { CollaborationCloudReadOnlyBanner } from '../components/transcription/CollaborationCloudReadOnlyBanner';
import {
  buildReadyWorkspaceSidePaneProps,
  buildReadyWorkspaceWaveformContentProps,
  buildReadyWorkspaceOverlaysProps,
  buildReadyWorkspaceLayoutStyle,
  buildReadyWorkspaceStageProps,
} from './transcriptionReadyWorkspacePropsBuilders';
import {
  buildReadyWorkspaceSidePanePropsInput,
  buildReadyWorkspaceWaveformContentPropsInput,
  buildReadyWorkspaceOverlaysPropsInput,
  buildReadyWorkspaceLayoutStyleInput,
  buildReadyWorkspaceStagePropsInput,
} from './transcriptionReadyWorkspaceSurfaceInputBuilder';
import type { BuildReadyWorkspaceOverlaysPropsInputFromControllers } from './transcriptionReadyWorkspaceOverlaysInputBuilder';
import type { BuildReadyWorkspaceStagePropsInputFromControllers } from './transcriptionReadyWorkspaceStagePropsInputBuilder';
import type { BuildReadyWorkspaceWaveformContentPropsInputFromControllers } from './transcriptionReadyWorkspaceWaveformInputBuilder';
import type {
  UseReadyWorkspaceSurfacePropsInput,
  UseReadyWorkspaceSurfacePropsResult,
} from './readyWorkspaceSurfacePropsTypes';

export function assembleReadyWorkspaceSurfacePropsBundle(
  input: UseReadyWorkspaceSurfacePropsInput,
): UseReadyWorkspaceSurfacePropsResult {
  const { overlays: o, controllers: c, layout: l, waveform: w } = input;
  const i = input as any;
  const timelineCtl = c.timeline as Record<string, unknown> | null | undefined;
  const batchCtl = c.batch as Record<string, unknown> | null | undefined;
  const selfCertaintyCtl = c.selfCertainty as Record<string, unknown> | null | undefined;

  const readyWorkspaceSidePaneProps = buildReadyWorkspaceSidePaneProps(
    buildReadyWorkspaceSidePanePropsInput({
      speakerActionScopeController: c.speakerActionScope,
      speakerController: c.speaker,
      sidePaneRows: i.orderedLayers,
      focusedLayerRowId: i.focusedLayerRowId,
      flashLayerRowId: i.flashLayerRowId,
      onFocusLayer: i.handleFocusLayerRow,
      transcriptionLayers: i.orderedLayers.filter(
        (layer: any) => layer.layerType === 'transcription',
      ),
      layerLinks: i.layerLinks,
      toggleLayerLink: i.toggleLayerLink,
      deletableLayers: i.deletableLayers,
      updateLayerMetadata: i.updateLayerMetadata,
      layerCreateMessage: i.layerCreateMessage,
      layerAction: i.layerAction,
      ...(i.defaultTranscriptionLayerId !== undefined
        ? { defaultTranscriptionLayerId: i.defaultTranscriptionLayerId }
        : {}),
      segmentsByLayer: i.segmentsByLayer,
      segmentContentByLayer: i.segmentContentByLayer,
      unitsOnCurrentMedia: i.unitsOnCurrentMedia,
      speakers: i.speakers,
      listProjectAssets: i.listProjectAssets,
      removeProjectAsset: i.removeProjectAsset,
      getProjectAssetSignedUrl: i.getProjectAssetSignedUrl,
      listProjectSnapshots: i.listProjectSnapshots,
      restoreProjectSnapshotToLocalById: i.restoreProjectSnapshotToLocalById,
      queryProjectChangeTimeline: i.queryProjectChangeTimeline,
      supabaseConfigured: hasSupabaseBrowserClientConfig(),
      activeTextId: i.activeTextId,
      listAccessibleCloudProjects: i.listAccessibleCloudProjects,
      listCloudProjectMembers: i.listCloudProjectMembers,
      getUnitTextForLayer: i.getUnitTextForLayer,
      onSelectTimelineUnit: i.selectTimelineUnit,
      onReorderLayers: i.reorderLayers,
      locale: i.locale,
      verticalViewActive: i.verticalViewActive,
      translationLayerCount: i.translationLayers.length,
      onSelectWorkspaceHorizontalLayout: i.onSelectWorkspaceHorizontalLayout,
      onSelectWorkspaceVerticalLayout: i.onSelectWorkspaceVerticalLayout,
    } as any),
  );

  const readyWorkspaceWaveformContentProps = buildReadyWorkspaceWaveformContentProps(
    buildReadyWorkspaceWaveformContentPropsInput({
      locale: i.locale,
      waveformAreaRef: w.waveformAreaRef,
      snapGuideNearSide: w.snapGuide?.nearSide,
      segMarkStart: w.segMarkStart,
      isResizingWaveform: w.isResizingWaveform,
      waveformHeight: w.waveformHeight,
      handleWaveformKeyDown: w.handleWaveformKeyDown,
      handleWaveformAreaFocus: w.handleWaveformAreaFocus,
      handleWaveformAreaBlur: w.handleWaveformAreaBlur,
      handleWaveformAreaMouseMove: w.handleWaveformAreaMouseMove,
      handleWaveformAreaMouseLeave: w.handleWaveformAreaMouseLeave,
      handleWaveformAreaWheel: w.handleWaveformAreaWheel,
      hoverTime: w.hoverTime,
      unitsOnCurrentMedia: i.unitsOnCurrentMedia,
      getUnitTextForLayer: i.getUnitTextForLayer,
      waveformHoverPreviewProps: w.waveformHoverPreviewProps,
      selectedMediaUrl: i.selectedMediaUrl,
      zoomPercent: w.zoomPercent,
      snapEnabled: w.snapEnabled,
      toggleSnapEnabled: w.toggleSnapEnabled,
      playerPlaybackRate: w.playerPlaybackRate,
      amplitudeScale: w.amplitudeScale,
      setAmplitudeScale: w.setAmplitudeScale,
      selectedMediaIsVideo: w.selectedMediaIsVideo,
      videoLayoutMode: w.videoLayoutMode,
      setVideoLayoutMode: w.setVideoLayoutMode,
      handleLaneLabelWidthResizeStart: w.handleLaneLabelWidthResizeStart,
      videoPreviewHeight: w.videoPreviewHeight,
      videoRightPanelWidth: w.videoRightPanelWidth,
      waveformRegions: w.waveformRegions,
      selectedUnitIds: w.selectedUnitIds,
      activeTimelineUnitId: w.activeTimelineUnitId,
      segmentLoopPlayback: w.segmentLoopPlayback,
      subSelectionRange: w.subSelectionRange,
      isResizingVideoPreview: w.isResizingVideoPreview,
      isResizingVideoRightPanel: w.isResizingVideoRightPanel,
      handleVideoPreviewResizeStart: w.handleVideoPreviewResizeStart,
      handleVideoRightPanelResizeStart: w.handleVideoRightPanelResizeStart,
      waveformDisplayMode: w.waveformDisplayMode,
      waveCanvasRef: w.waveCanvasRef,
      waveformStripWheelShellRef: w.waveformStripWheelShellRef,
      segmentRangeGesturePreviewReadModel: w.segmentRangeGesturePreviewReadModel,
      waveformNoteIndicators: w.waveformNoteIndicators,
      waveformLowConfidenceOverlays: w.waveformLowConfidenceOverlays,
      waveformOverlapOverlays: w.waveformOverlapOverlays,
      acousticOverlayMode: w.acousticOverlayMode,
      acousticOverlayViewportWidth: w.acousticOverlayViewportWidth,
      acousticOverlayF0Path: w.acousticOverlayF0Path,
      acousticOverlayIntensityPath: w.acousticOverlayIntensityPath,
      acousticOverlayVisibleSummary: w.acousticOverlayVisibleSummary,
      acousticOverlayLoading: w.acousticOverlayLoading,
      waveformHoverReadout: w.waveformHoverReadout,
      spectrogramHoverReadout: w.spectrogramHoverReadout,
      selectedHotspotTimeSec: w.selectedHotspotTimeSec,
      handleSpectrogramMouseMove: w.handleSpectrogramMouseMove,
      handleSpectrogramMouseLeave: w.handleSpectrogramMouseLeave,
      handleSpectrogramClick: w.handleSpectrogramClick,
      setNotePopover: i.setNotePopover,
      selectedWaveformTimelineItem: w.selectedWaveformTimelineItem,
      playerInstanceGetWidth: w.playerInstanceGetWidth,
      waveformScrollLeft: w.waveformScrollLeft,
      segmentPlaybackRate: w.segmentPlaybackRate,
      handleSegmentPlaybackRateChange: w.handleSegmentPlaybackRateChange,
      handleToggleSelectedWaveformLoop: w.handleToggleSelectedWaveformLoop,
      handleToggleSelectedWaveformPlay: w.handleToggleSelectedWaveformPlay,
      selectedTimelineUnitForTime: w.selectedTimelineUnitForTime,
      runtimeStatus: w.runtimeStatus,
      snapGuide: {
        visible: w.snapGuide?.visible,
        left: w.snapGuide?.left,
        right: w.snapGuide?.right,
        nearSide: w.snapGuide?.nearSide,
      },
      playerBridge: {
        spectrogramRef: i.player?.spectrogramRef,
        waveformRef: i.player?.waveformRef,
        seekTo: i.player?.seekTo,
        playRegion: i.player?.playRegion,
        duration: i.player?.duration,
        isReady: i.player?.isReady,
        isPlaying: i.player?.isPlaying,
      },
      timelineViewportProjection: {
        rulerView: w.timelineViewportProjection?.rulerView,
        zoomPxPerSec: w.timelineViewportProjection?.zoomPxPerSec,
      },
      mediaFileInputRef: w.mediaFileInputRef,
      acousticStrip: w.acousticStrip,
    } as BuildReadyWorkspaceWaveformContentPropsInputFromControllers),
  );

  const readyWorkspaceOverlaysProps = buildReadyWorkspaceOverlaysProps(
    buildReadyWorkspaceOverlaysPropsInput({
      ctxMenu: o.ctxMenu,
      setCtxMenu: o.setCtxMenu,
      uttOpsMenu: o.uttOpsMenu,
      setUttOpsMenu: o.setUttOpsMenu,
      selectedTimelineUnit: o.selectedTimelineUnit ?? null,
      selectedUnitIds: o.selectedUnitIds,
      runDeleteSelection: o.runDeleteSelection,
      runMergeSelection: o.runMergeSelection,
      runSelectBefore: o.runSelectBefore,
      runSelectAfter: o.runSelectAfter,
      runDeleteOne: o.runDeleteOne,
      runMergePrev: o.runMergePrev,
      runMergeNext: o.runMergeNext,
      runSplitAtTime: o.runSplitAtTime,
      getCurrentTime: o.getCurrentTime,
      setNotePopover: o.setNotePopover,
      deleteConfirmState: o.deleteConfirmState,
      muteDeleteConfirmInSession: o.muteDeleteConfirmInSession,
      setMuteDeleteConfirmInSession: o.setMuteDeleteConfirmInSession,
      closeDeleteConfirmDialog: o.closeDeleteConfirmDialog,
      confirmDeleteFromDialog: o.confirmDeleteFromDialog,
      notePopover: o.notePopover,
      currentNotes: o.currentNotes,
      addNote: o.addNote,
      updateNote: o.updateNote,
      deleteNote: o.deleteNote,
      units: o.units,
      resolveSelfCertaintyUnitIds: selfCertaintyCtl?.resolveSelfCertaintyUnitIds,
      getUnitTextForLayer: o.getUnitTextForLayer,
      transcriptionLayers: o.transcriptionLayers,
      translationLayers: o.translationLayers,
      speakerOptions: o.speakerOptions,
      speakerFilterOptions: o.speakerFilterOptions,
      onAssignSpeakerFromMenu: o.onAssignSpeakerFromMenu,
      onSetUnitSelfCertaintyFromMenu: o.onSetUnitSelfCertaintyFromMenu,
      timelineUnitsOnCurrentMedia: o.timelineUnitsOnCurrentMedia,
      toggleSkipProcessingRouted: o.toggleSkipProcessingRouted,
      onOpenSpeakerManagementPanelFromMenu: o.onOpenSpeakerManagementPanelFromMenu,
      displayStyleControl: o.displayStyleControl,
    } as BuildReadyWorkspaceOverlaysPropsInputFromControllers),
  );

  const readyWorkspaceLayoutStyle = buildReadyWorkspaceLayoutStyle(
    buildReadyWorkspaceLayoutStyleInput({
      uiFontScale: l.uiFontScale,
      adaptiveDialogWidth: l.adaptiveDialogWidth,
      adaptiveDialogCompactWidth: l.adaptiveDialogCompactWidth,
      adaptiveDialogWideWidth: l.adaptiveDialogWideWidth,
      aiPanelWidth: l.aiPanelWidth,
      isAiPanelCollapsed: l.isAiPanelCollapsed,
      laneLabelWidth: l.laneLabelWidth,
      isTimelineLaneHeaderCollapsed: l.isTimelineLaneHeaderCollapsed,
      selectedMediaUrl: l.selectedMediaUrl,
      selectedMediaIsVideo: l.selectedMediaIsVideo,
      videoLayoutMode: l.videoLayoutMode,
      videoRightPanelWidth: l.videoRightPanelWidth,
    }),
  );

  const readyWorkspaceStageProps = buildReadyWorkspaceStageProps(
    buildReadyWorkspaceStagePropsInput({
      assistantFrame: i.assistantSidebarController?.assistantRuntimeProps?.frame,
      shouldRenderRecoveryBanner: i.readyWorkspaceRenderController?.shouldRenderRecoveryBanner,
      recoveryAvailable: i.recoveryAvailable,
      recoveryDiffSummary: i.recoveryDiffSummary,
      onApplyRecoveryBanner: i.applyRecoveryBanner,
      onDismissRecoveryBanner: i.dismissRecoveryBanner,
      collaborationCloudStatusSlot: (
        <CollaborationCloudReadOnlyBanner
          locale={i.locale as any}
          guard={i.collaborationProtocolGuard as any}
        />
      ),
      toolbarProps: i.toolbarPropsWithCollaboration,
      observerStage: i.observerResult?.stage,
      recommendations: i.actionableObserverRecommendations || [],
      onExecuteRecommendation: i.handleExecuteObserverRecommendation,
      acousticRuntimeStatus: i.deferredAiRuntime?.acousticRuntimeStatus,
      vadCacheStatus: i.vadCacheStatus,
      currentProjectLabel: i.readyWorkspaceViewModels?.toolbarProps?.filename,
      ...(i.selectedTimelineMedia !== undefined
        ? { selectedTimelineMedia: i.selectedTimelineMedia }
        : {}),
      activeTextTimelineMode: i.activeTextTimelineMode,
      activeTextTimeMapping: i.activeTextTimeMapping,
      canDeleteProject: Boolean(i.activeTextId),
      ...(i.selectedMediaUrl !== undefined ? { selectedMediaUrl: i.selectedMediaUrl } : {}),
      setShowProjectSetup: i.setShowProjectSetup,
      setShowAudioImport: i.setShowAudioImport,
      speakerController: c.speaker,
      projectMediaController: c.projectMedia,
      importExportController: c.importExport,
      applyTextTimeMapping: i.applyTextTimeMapping,
      ...(i.segmentScopeMediaId ? { segmentScopeMediaId: i.segmentScopeMediaId } : {}),
      waveformSectionRef: w.waveformSectionRef,
      workspaceRef: w.workspaceRef,
      listMainRef: w.listMainRef,
      tierContainerRef: w.acousticStrip?.tierContainerRef,
      isAiPanelCollapsed: l.isAiPanelCollapsed,
      isTimelineLaneHeaderCollapsed: l.isTimelineLaneHeaderCollapsed,
      readyWorkspaceWaveformContentProps,
      timelineTopProps: i.readyWorkspaceAxisStatusController?.timelineTopPropsWithAxisStatus,
      readyWorkspaceSidePaneProps,
      timelineContentProps: i.readyWorkspaceViewModels?.timelineContentProps,
      editorContextValue: timelineCtl?.editorContextValue,
      aiPanelContextValue: i.assistantController?.aiPanelContextValue,
      onLassoPointerDown: i.handleLassoPointerDown,
      onLassoPointerMove: i.handleLassoPointerMove,
      onLassoPointerUp: i.handleLassoPointerUp,
      onTimelineScroll: i.handleTimelineScroll,
      timelineResizeTooltip: i.timelineResizeController?.timelineResizeTooltip,
      formatTime: i.formatTime,
      timelineViewportProjection: i.timelineViewportProjection,
      snapEnabled: i.snapEnabled,
      autoScrollEnabled: i.autoScrollEnabled,
      activeWaveformRegionId: i.selectedWaveformRegionId,
      waveformTimelineItems: i.waveformTimelineItems,
      onZoomToPercent: (percent: number, mode: 'fit-all' | 'fit-selection' | 'custom') =>
        i.zoomToPercent(percent, undefined, mode),
      onZoomToUnit: i.zoomToUnit,
      onSnapEnabledChange: i.setSnapEnabled,
      onAutoScrollEnabledChange: i.setAutoScrollEnabled,
      canUndo: i.canUndo,
      canRedo: i.canRedo,
      undoLabel: i.undoLabel,
      undoHistory: i.undoHistory,
      isHistoryVisible: i.showUndoHistory,
      onToggleHistoryVisible: i.setShowUndoHistory,
      selectedTimelineUnit: i.selectedTimelineUnit,
      activeTimelineUnitId: i.activeTimelineUnitId,
      recordTimelineEdit: i.recordTimelineEdit,
      undoToHistoryIndex: i.undoToHistoryIndex,
      redo: i.redo,
      locale: i.locale,
      setIsAiPanelCollapsed: i.setIsAiPanelCollapsed,
      handleAiPanelResizeStart: i.workspacePanelEffectsController?.handleAiPanelResizeStart,
      handleAiPanelToggle: i.handleAiPanelToggle,
      assistantBridgeControllerInput: i.assistantBridgeControllerInput,
      onRuntimeStateChange: i.handleDeferredAiRuntimeChange,
      aiSidebarProps: i.readyWorkspaceViewModels?.aiSidebarProps,
      shouldRenderAiSidebar: i.readyWorkspaceRenderController?.shouldRenderAiSidebar,
      dialogsProps: i.readyWorkspaceViewModels?.dialogsProps,
      shouldRenderDialogs: i.readyWorkspaceRenderController?.shouldRenderDialogs,
      pdfRuntimeProps: i.assistantSidebarController?.pdfRuntimeProps,
      shouldRenderPdfRuntime: i.readyWorkspaceRenderController?.shouldRenderPdfRuntime,
      shouldRenderBatchOps: i.readyWorkspaceRenderController?.shouldRenderBatchOps,
      showBatchOperationPanel: i.showBatchOperationPanel,
      selectedUnitIds: i.selectedUnitIds,
      selectedBatchUnits: batchCtl?.selectedBatchUnits,
      unitsOnCurrentMedia: i.unitsOnCurrentMedia,
      selectedBatchUnitTextById: timelineCtl?.selectedBatchUnitTextById,
      batchPreviewLayerOptions: timelineCtl?.batchPreviewLayerOptions,
      batchPreviewTextByLayerId: timelineCtl?.batchPreviewTextByLayerId,
      batchPreviewTextPropsByLayerId: i.batchPreviewTextPropsByLayerId,
      defaultBatchPreviewLayerId: timelineCtl?.defaultBatchPreviewLayerId,
      onCloseBatchOps: () => i.setShowBatchOperationPanel(false),
      onBatchOffset: batchCtl?.handleBatchOffset,
      onBatchScale: batchCtl?.handleBatchScale,
      onBatchSplitByRegex: batchCtl?.handleBatchSplitByRegex,
      onBatchMerge: batchCtl?.handleBatchMerge,
      onBatchJumpToUnit: i.selectUnit,
    } as BuildReadyWorkspaceStagePropsInputFromControllers),
  );

  return {
    readyWorkspaceSidePaneProps,
    readyWorkspaceWaveformContentProps,
    readyWorkspaceOverlaysProps,
    readyWorkspaceLayoutStyle,
    readyWorkspaceStageProps,
  };
}
