import type { Dispatch, MutableRefObject, RefObject, SetStateAction } from 'react';
import type { AcousticOverlayMode } from '../utils/acousticOverlayTypes';
import type { OrthographyDocType, LayerUnitDocType } from '../db';
import type { TimelineUnit } from '../hooks/transcriptionTypes';
import type { AppShellOpenSearchDetail } from '../utils/appShellEvents';
import type { WaveformDisplayMode } from '../utils/waveformDisplayMode';
import type { WaveformVisualStyle } from '../utils/waveformVisualStyle';
import type WaveSurfer from 'wavesurfer.js';
import type { UttOpsMenuState } from './TranscriptionPage.UIState';
import type { TranscriptionPageTimelineContentProps } from './TranscriptionPage.TimelineContent';
import type { TranscriptionPageTimelineTopProps } from './TranscriptionPage.TimelineTop';
import type { TranscriptionPageToolbarProps } from './TranscriptionPage.Toolbar';
import type { UseTranscriptionSidebarSectionsViewModelInput } from './useTranscriptionSidebarSectionsViewModel';

export interface UseTranscriptionSectionViewModelsInput {
  locale: string;
  selectedTimelineMediaFilename: string | null;
  player: {
    isReady: boolean;
    isPlaying: boolean;
    stop: () => void;
    playbackRate: number;
    setPlaybackRate: (rate: number) => void;
    volume: number;
    setVolume: (volume: number) => void;
    seekBySeconds: (delta: number) => void;
    seekTo: (time: number) => void;
    currentTime: number;
    duration: number;
    instanceRef: RefObject<WaveSurfer | null>;
  };
  waveformDisplayMode: WaveformDisplayMode;
  setWaveformDisplayMode: (mode: WaveformDisplayMode) => void;
  waveformVisualStyle: WaveformVisualStyle;
  setWaveformVisualStyle: (style: WaveformVisualStyle) => void;
  acousticOverlayMode: AcousticOverlayMode;
  setAcousticOverlayMode: (mode: AcousticOverlayMode) => void;
  globalLoopPlayback: boolean;
  setGlobalLoopPlayback: (loop: boolean) => void;
  handleGlobalPlayPauseAction: () => void;
  canUndo: boolean;
  canRedo: boolean;
  undoLabel: string;
  hasSelectedTimelineMedia: boolean;
  hasActiveTextId: boolean;
  selectedTimelineUnit: TimelineUnit | null;
  notePopoverOpen: boolean;
  showExportMenu: boolean;
  importFileRef: RefObject<HTMLInputElement | null>;
  exportMenuRef: RefObject<HTMLDivElement | null>;
  loadSnapshot: () => Promise<void>;
  undo: () => Promise<void>;
  redo: () => Promise<void>;
  setShowProjectSetup: (value: boolean) => void;
  setShowAudioImport: (value: boolean) => void;
  handleDeleteCurrentAudio: () => void;
  handleDeleteCurrentProject: () => void;
  toggleNotes: () => void;
  setUttOpsMenu: (state: UttOpsMenuState | null) => void;
  selectedMediaUrl: string | null;
  playableAcoustic: boolean;
  handleAutoSegment: () => void;
  autoSegmentBusy: boolean;
  setShowExportMenu: Dispatch<SetStateAction<boolean>>;
  handleExportEaf: () => void;
  handleExportTextGrid: () => void;
  handleExportTrs: () => void;
  handleExportFlextext: () => void;
  handleExportToolbox: () => void;
  handleExportJyt: () => Promise<void>;
  handleExportJym: () => Promise<void>;
  handleImportFile: (file: File) => Promise<void>;
  unitsOnCurrentMedia: LayerUnitDocType[];
  rulerView: { start: number; end: number } | null;
  zoomPxPerSec: number;
  isTimelineLaneHeaderCollapsed: boolean;
  toggleTimelineLaneHeader: () => void;
  waveCanvasRef: RefObject<HTMLDivElement | null>;
  tierContainerRef: RefObject<HTMLDivElement | null>;
  showSearch: boolean;
  searchableItems: TranscriptionPageTimelineTopProps['searchProps']['items'];
  orthographies: OrthographyDocType[];
  activeLayerIdForEdits: string;
  activeTimelineUnitId: string;
  searchOverlayRequest: AppShellOpenSearchDetail | null;
  manualSelectTsRef: MutableRefObject<number>;
  selectUnit: (id: string) => void;
  handleSearchReplace: (unitId: string, layerId: string | undefined, oldText: string, newText: string) => void;
  setShowSearch: (value: boolean) => void;
  setSearchOverlayRequest: Dispatch<SetStateAction<AppShellOpenSearchDetail | null>>;
  timelineContentProps: TranscriptionPageTimelineContentProps;
  sidebarSectionsInput: UseTranscriptionSidebarSectionsViewModelInput;
}

export interface UseTranscriptionSectionViewModelsResult {
  toolbarProps: TranscriptionPageToolbarProps;
  timelineTopProps: TranscriptionPageTimelineTopProps;
  timelineContentProps: TranscriptionPageTimelineContentProps;
}