import { describe, expect, it, vi } from 'vitest';
import type { TranscriptionReadyWorkspaceOrchestratorRawInput } from './transcriptionReadyWorkspaceOrchestratorInput';
import { buildOrchestratorViewModelsInput } from './transcriptionReadyWorkspaceOrchestratorInput';

function makeInput(overrides?: Partial<TranscriptionReadyWorkspaceOrchestratorRawInput>): TranscriptionReadyWorkspaceOrchestratorRawInput {
  const base = {
    selectedMediaUrl: 'blob:test',
    playableAcoustic: true,
    timelineExtentSec: 123,
    player: { isReady: true, duration: 90 } as unknown,
    layers: [{ id: 'layer-1' }],
    locale: 'zh-CN',
    importFileRef: { current: null },
    layerAction: { setLayerActionPanel: vi.fn() },
    sharedLaneProps: {
      timelineContentGutterPx: 64,
      transcriptionLayers: [],
      translationLayers: [],
      timelineUnitViewIndex: { epoch: 0, byId: new Map(), orderedIds: [] },
      allLayersOrdered: [],
      onReorderLayers: vi.fn(async () => {}),
      speakerOptionsByLayerId: new Map(),
      speakerMap: new Map(),
      orthographiesByLanguageTag: new Map(),
      languageTagByLayerId: new Map(),
      timelineViewConfigByLayerId: new Map(),
      displayStyleControl: { orthographies: [] },
      activeTextTimelineMode: 'document',
      setActiveTextTimelineMode: vi.fn(),
      activeLayerIdForEdits: null,
      waveContainerClassName: undefined,
      audioReady: true,
      selectUnit: vi.fn(),
      selectedUnitId: '',
      selectedUnitIds: new Set(),
      utteranceDrafts: {},
      utteranceSaveStatus: {},
      utteranceToolStatus: {},
      pendingSegmentDeleteIds: new Set(),
      pendingSegmentDeleteCountByRowId: new Map(),
      pendingLayerDeleteIds: new Set(),
      pendingLayerDeleteCountByRowId: new Map(),
      onDeleteLayerWithConfirm: vi.fn(),
      onDeleteSegmentWithConfirm: vi.fn(),
      onRetrySegmentDelete: vi.fn(),
      onLayerOperationAction: vi.fn(),
      onCreateSegmentInLayer: vi.fn(async () => {}),
      setCollapsed: vi.fn(),
      collapsedLayerIds: new Set(),
      layerRowClassNameById: {},
      saveUtterance: vi.fn(async () => {}),
      handleSegmentUpdate: vi.fn(async () => {}),
      handleSegmentSplitAtPlayhead: vi.fn(async () => {}),
      handleSegmentMergeWithPrevious: vi.fn(async () => {}),
      handleSegmentDelete: vi.fn(async () => {}),
      layerLinks: [],
      media: [],
      selectedMedia: undefined,
      layersById: new Map(),
      orthographiesByLayerId: new Map(),
      sourceLayerByLayerId: new Map(),
      transcriptionLayerIds: [],
      translationLayerIds: [],
      uiStateByLayerId: new Map(),
      segmentListByLayerMedia: {},
      levelStatsByLayerId: new Map(),
      activeSegmentId: null,
      onSeekSegment: vi.fn(),
      onFocusSegment: vi.fn(),
      onOpenSegmentContextMenu: vi.fn(),
      onFocusTimelineLayer: vi.fn(),
      onToggleLayerVisibility: vi.fn(),
      onToggleLayerLock: vi.fn(),
      onToggleLayerMute: vi.fn(),
      onSetLayerHeight: vi.fn(),
      onSetLayerDisplayMode: vi.fn(),
      onSetLayerSortKey: vi.fn(),
      onToggleGroupCollapsed: vi.fn(),
      onSetSpeakerColor: vi.fn(),
      onSetSpeakerAlias: vi.fn(),
      onReorderSpeakers: vi.fn(),
      onSetLayerSpeakerByUnit: vi.fn(),
      onSetLayerNoteByUnit: vi.fn(),
      onSetLayerTagByUnit: vi.fn(),
      onRenameLayer: vi.fn(),
      onCreateLayer: vi.fn(),
      onDuplicateLayer: vi.fn(),
      onArchiveLayer: vi.fn(),
      onRestoreLayer: vi.fn(),
      onSelectLayer: vi.fn(),
      onSetLayerOrthography: vi.fn(),
      onSetLayerLanguageTag: vi.fn(),
      onSetLayerTimelineMode: vi.fn(),
      onToggleOverlay: vi.fn(),
      onSetOverlayOpacity: vi.fn(),
      onSetOverlayScale: vi.fn(),
      onSetOverlayThreshold: vi.fn(),
      onSetOverlayColor: vi.fn(),
      onSetOverlayStyle: vi.fn(),
      onSetOverlayAnchor: vi.fn(),
      onSetOverlayOffset: vi.fn(),
      onSetOverlaySmoothing: vi.fn(),
      onSetOverlayWindow: vi.fn(),
      onSetOverlaySampleRate: vi.fn(),
      onSetOverlayChannels: vi.fn(),
      onSetOverlayBand: vi.fn(),
      onSetOverlayNoiseFloor: vi.fn(),
      onSetOverlayGain: vi.fn(),
      onSetOverlayContrast: vi.fn(),
      onSetOverlayGamma: vi.fn(),
    },
    timelineViewportProjection: {
      zoomPxPerSec: 25,
      documentSpanSec: 200,
      zoomPercent: 100,
      maxZoomPercent: 400,
      fitPxPerSec: 25,
      rulerView: { start: 0, end: 8 },
      viewportFrame: { scrollLeftPx: 0, pxPerDocSec: 25, visibleStartSec: 0, visibleEndSec: 8 },
    },
    segmentRangeGesturePreviewReadModel: { surface: 'none' },
    timelineRenderUnits: [],
    defaultTranscriptionLayerId: 'layer-1',
    textOnlyLogicalDurationSec: 200,
    textOnlyTimeMapping: { offsetSec: 0, scale: 1 },
    createUnitFromSelectionRouted: vi.fn(async () => {}),
    renderAnnotationItem: vi.fn(),
    speakerSortKeyById: {},
    filteredUnitsOnCurrentMedia: [],
    tierContainerRef: { current: null },
    handleAnnotationClick: vi.fn(),
    handleAnnotationContextMenu: vi.fn(),
    handleNoteClick: vi.fn(),
    resolveNoteIndicatorTarget: vi.fn(),
    startTimelineResizeDrag: vi.fn(),
    navigateUnitFromInput: vi.fn(),
    speakerVisualByTimelineUnitId: {},
    resolveSelfCertaintyForUnit: vi.fn(),
    resolveSelfCertaintyAmbiguityForUnit: vi.fn(),
    verticalViewEnabled: false,
    verticalPaneFocus: undefined,
    updateVerticalPaneFocus: undefined,
    selectedTimelineMedia: undefined,
    waveformDisplayMode: 'waveform',
    setWaveformDisplayMode: vi.fn(),
    waveformVisualStyle: 'classic',
    setWaveformVisualStyle: vi.fn(),
    acousticOverlayMode: 'off',
    setAcousticOverlayMode: vi.fn(),
    globalLoopPlayback: false,
    setGlobalLoopPlayback: vi.fn(),
    handleGlobalPlayPauseAction: vi.fn(),
    canUndo: false,
    canRedo: false,
    undoLabel: '',
    activeTextId: null,
    selectedTimelineUnit: null,
    notePopover: null,
    showExportMenu: false,
    exportMenuRef: { current: null },
    loadSnapshot: vi.fn(),
    undo: vi.fn(),
    redo: vi.fn(),
    setShowProjectSetup: vi.fn(),
    setShowAudioImport: vi.fn(),
    handleDeleteCurrentAudio: vi.fn(),
    handleDeleteCurrentProject: vi.fn(),
    toggleNotes: vi.fn(),
    setUttOpsMenu: vi.fn(),
    handleAutoSegment: vi.fn(),
    autoSegmentBusy: false,
    setShowExportMenu: vi.fn(),
    handleExportEaf: vi.fn(),
    handleExportTextGrid: vi.fn(),
    handleExportTrs: vi.fn(),
    handleExportFlextext: vi.fn(),
    handleExportToolbox: vi.fn(),
    handleExportJyt: vi.fn(),
    handleExportJym: vi.fn(),
    handleImportFile: vi.fn(),
    unitsOnCurrentMedia: [],
    isTimelineLaneHeaderCollapsed: false,
    toggleTimelineLaneHeader: vi.fn(),
    waveCanvasRef: { current: null },
    showSearch: false,
    searchableItems: [],
    displayStyleControl: { orthographies: [] },
    activeLayerIdForEdits: null,
    activeTimelineUnitId: '',
    searchOverlayRequest: null,
    manualSelectTsRef: { current: 0 },
    selectUnit: vi.fn(),
    handleSearchReplace: vi.fn(),
    setShowSearch: vi.fn(),
    setSearchOverlayRequest: vi.fn(),
    isAiPanelCollapsed: false,
    hubSidebarTab: 'assistant',
    setHubSidebarTab: vi.fn(),
    assistantRuntimeProps: {} as unknown,
    analysisRuntimeProps: {} as unknown,
    selectedAiWarning: false,
    selectedTranslationGapCount: 0,
    aiSidebarError: null,
    speakerDialogStateRouted: null,
    speakerSavingRouted: false,
    closeSpeakerDialogRouted: vi.fn(),
    confirmSpeakerDialogRouted: vi.fn(async () => {}),
    updateSpeakerDialogDraftNameRouted: vi.fn(),
    updateSpeakerDialogTargetKeyRouted: vi.fn(),
    showProjectSetup: false,
    handleProjectSetupSubmit: vi.fn(async () => {}),
    showAudioImport: false,
    handleAudioImport: vi.fn(),
    audioImportDisposition: null,
    mediaFileInputRef: { current: null },
    handleDirectMediaImport: vi.fn(),
    audioDeleteConfirm: null,
    setAudioDeleteConfirm: vi.fn(),
    handleConfirmAudioDelete: vi.fn(),
    projectDeleteConfirm: false,
    setProjectDeleteConfirm: vi.fn(),
    handleConfirmProjectDelete: vi.fn(),
    showShortcuts: false,
    closeShortcuts: vi.fn(),
    isFocusMode: false,
    exitFocusMode: vi.fn(),
  } as unknown as TranscriptionReadyWorkspaceOrchestratorRawInput;

  return { ...base, ...overrides };
}

describe('buildOrchestratorViewModelsInput', () => {
  it('bridges timelineExtentSec to orchestrator view-model input', () => {
    const result = buildOrchestratorViewModelsInput(makeInput({ timelineExtentSec: 345 }));
    expect(result.timelineExtentSec).toBe(345);
  });

  it('does not expose removed textTimelineZoomPxPerSec contract in vertical mode', () => {
    const result = buildOrchestratorViewModelsInput(makeInput({ verticalViewEnabled: true }));
    const textOnly = result.textOnlyPropsInput as Record<string, unknown>;
    expect(textOnly.textTimelineZoomPxPerSec).toBeUndefined();
  });

  it('does not expose removed textTimelineZoomPxPerSec contract in non-vertical mode', () => {
    const result = buildOrchestratorViewModelsInput(makeInput({ verticalViewEnabled: false }));
    const textOnly = result.textOnlyPropsInput as Record<string, unknown>;
    expect(textOnly.textTimelineZoomPxPerSec).toBeUndefined();
  });

  it('derives media lane lassoRect from segment-range gesture preview read model', () => {
    const result = buildOrchestratorViewModelsInput(makeInput({
      segmentRangeGesturePreviewReadModel: { surface: 'tier', rect: { x: 1, y: 2, w: 3, h: 4 } },
    }));
    const media = result.mediaLanesPropsInput as Record<string, unknown>;
    expect(media.lassoRect).toEqual({ x: 1, y: 2, w: 3, h: 4 });
  });

  it('derives text-only timingDragPreview from timeRange surface', () => {
    const result = buildOrchestratorViewModelsInput(makeInput({
      segmentRangeGesturePreviewReadModel: { surface: 'timeRange', preview: { id: 'u1', start: 1, end: 2 } },
    }));
    const textOnly = result.textOnlyPropsInput as Record<string, unknown>;
    expect(textOnly.timingDragPreview).toEqual({ id: 'u1', start: 1, end: 2 });
  });
});
