import { useMemo } from 'react';
import type { UseTranscriptionSectionViewModelsInput } from './transcriptionSectionViewModelTypes';

type UseTranscriptionSectionViewModelsInputBase = Omit<UseTranscriptionSectionViewModelsInput, 'sidebarSectionsInput'>;

export function useTranscriptionSectionViewModelsInput(
  input: UseTranscriptionSectionViewModelsInputBase,
): UseTranscriptionSectionViewModelsInputBase {
  return useMemo<UseTranscriptionSectionViewModelsInputBase>(() => ({
    locale: input.locale,
    selectedTimelineMediaFilename: input.selectedTimelineMediaFilename,
    player: input.player,
    waveformDisplayMode: input.waveformDisplayMode,
    setWaveformDisplayMode: input.setWaveformDisplayMode,
    waveformVisualStyle: input.waveformVisualStyle,
    setWaveformVisualStyle: input.setWaveformVisualStyle,
    acousticOverlayMode: input.acousticOverlayMode,
    setAcousticOverlayMode: input.setAcousticOverlayMode,
    globalLoopPlayback: input.globalLoopPlayback,
    setGlobalLoopPlayback: input.setGlobalLoopPlayback,
    handleGlobalPlayPauseAction: input.handleGlobalPlayPauseAction,
    canUndo: input.canUndo,
    canRedo: input.canRedo,
    undoLabel: input.undoLabel,
    hasSelectedTimelineMedia: input.hasSelectedTimelineMedia,
    hasActiveTextId: input.hasActiveTextId,
    selectedTimelineUnit: input.selectedTimelineUnit,
    notePopoverOpen: input.notePopoverOpen,
    showExportMenu: input.showExportMenu,
    importFileRef: input.importFileRef,
    exportMenuRef: input.exportMenuRef,
    loadSnapshot: input.loadSnapshot,
    undo: input.undo,
    redo: input.redo,
    setShowProjectSetup: input.setShowProjectSetup,
    setShowAudioImport: input.setShowAudioImport,
    handleDeleteCurrentAudio: input.handleDeleteCurrentAudio,
    handleDeleteCurrentProject: input.handleDeleteCurrentProject,
    toggleNotes: input.toggleNotes,
    setUttOpsMenu: input.setUttOpsMenu,
    selectedMediaUrl: input.selectedMediaUrl,
    handleAutoSegment: input.handleAutoSegment,
    autoSegmentBusy: input.autoSegmentBusy,
    setShowExportMenu: input.setShowExportMenu,
    handleExportEaf: input.handleExportEaf,
    handleExportTextGrid: input.handleExportTextGrid,
    handleExportTrs: input.handleExportTrs,
    handleExportFlextext: input.handleExportFlextext,
    handleExportToolbox: input.handleExportToolbox,
    handleExportJyt: input.handleExportJyt,
    handleExportJym: input.handleExportJym,
    handleImportFile: input.handleImportFile,
    utterancesOnCurrentMedia: input.utterancesOnCurrentMedia,
    rulerView: input.rulerView,
    zoomPxPerSec: input.zoomPxPerSec,
    isTimelineLaneHeaderCollapsed: input.isTimelineLaneHeaderCollapsed,
    toggleTimelineLaneHeader: input.toggleTimelineLaneHeader,
    waveCanvasRef: input.waveCanvasRef,
    tierContainerRef: input.tierContainerRef,
    showSearch: input.showSearch,
    searchableItems: input.searchableItems,
    orthographies: input.orthographies,
    activeLayerIdForEdits: input.activeLayerIdForEdits,
    selectedTimelineUtteranceId: input.selectedTimelineUtteranceId,
    searchOverlayRequest: input.searchOverlayRequest,
    manualSelectTsRef: input.manualSelectTsRef,
    selectUtterance: input.selectUtterance,
    handleSearchReplace: input.handleSearchReplace,
    setShowSearch: input.setShowSearch,
    setSearchOverlayRequest: input.setSearchOverlayRequest,
    timelineContentProps: input.timelineContentProps,
  }), [
    input.activeLayerIdForEdits,
    input.autoSegmentBusy,
    input.canRedo,
    input.canUndo,
    input.exportMenuRef,
    input.globalLoopPlayback,
    input.handleAutoSegment,
    input.handleDeleteCurrentAudio,
    input.handleDeleteCurrentProject,
    input.handleExportEaf,
    input.handleExportFlextext,
    input.handleExportJym,
    input.handleExportJyt,
    input.handleExportTextGrid,
    input.handleExportToolbox,
    input.handleExportTrs,
    input.handleGlobalPlayPauseAction,
    input.handleImportFile,
    input.handleSearchReplace,
    input.hasActiveTextId,
    input.hasSelectedTimelineMedia,
    input.importFileRef,
    input.isTimelineLaneHeaderCollapsed,
    input.loadSnapshot,
    input.locale,
    input.manualSelectTsRef,
    input.notePopoverOpen,
    input.orthographies,
    input.player,
    input.setWaveformDisplayMode,
    input.setWaveformVisualStyle,
    input.setAcousticOverlayMode,
    input.redo,
    input.rulerView,
    input.searchOverlayRequest,
    input.searchableItems,
    input.selectedMediaUrl,
    input.selectedTimelineMediaFilename,
    input.selectedTimelineUnit,
    input.selectedTimelineUtteranceId,
    input.selectUtterance,
    input.setGlobalLoopPlayback,
    input.setSearchOverlayRequest,
    input.setShowAudioImport,
    input.setShowExportMenu,
    input.setShowProjectSetup,
    input.setShowSearch,
    input.setUttOpsMenu,
    input.showExportMenu,
    input.showSearch,
    input.tierContainerRef,
    input.timelineContentProps,
    input.toggleNotes,
    input.toggleTimelineLaneHeader,
    input.undo,
    input.undoLabel,
    input.utterancesOnCurrentMedia,
    input.waveCanvasRef,
    input.acousticOverlayMode,
    input.waveformDisplayMode,
    input.waveformVisualStyle,
    input.zoomPxPerSec,
  ]);
}
