function pageControllerRule(name, limits = {}) {
  return {
    file: `src/pages/${name}.ts`,
    requiredRegexes: [new RegExp(`export function ${name}\\(`)],
    ...limits,
  };
}

function hookRule(name, limits = {}) {
  return {
    file: `src/hooks/${name}.ts`,
    requiredRegexes: [new RegExp(`export function ${name}\\(`)],
    ...limits,
  };
}

function patternRule(matchRegex, limits = {}) {
  return {
    matchRegex,
    ...limits,
  };
}

export const architectureGuardRules = [
  // ── Orchestrator: 轻量壳，仅装载数据并渲染 ReadyWorkspace | Lightweight shell ──
  {
    file: 'src/pages/TranscriptionPage.Orchestrator.tsx',
    maxLines: 100,
    maxUseCallbackDecls: 0,
    maxUseMemoDecls: 0,
    maxUseEffects: 0,
  },
  // ── ReadyWorkspace: 承载全部运行时 hook 与 JSX | Runtime workspace with all hooks ──
  {
    file: 'src/pages/TranscriptionPage.ReadyWorkspace.tsx',
    maxLines: 2600,
    maxUseCallbackDecls: 8,
    maxUseMemoDecls: 10,
    maxUseEffects: 8,
    maxRegexMatchCounts: [
      {
        label: 'direct ../services imports',
        pattern: /^import .* from '\.\.\/services\//gm,
        max: 3,
      },
      {
        label: 'LinguisticService direct calls',
        pattern: /LinguisticService\./g,
        max: 6,
      },
      {
        label: 'LayerSegmentationV2Service direct content writes',
        pattern: /LayerSegmentationV2Service\.(deleteSegmentContent|upsertSegmentContent)\(/g,
        max: 2,
      },
      {
        label: 'LayerSegmentGraphService direct helper calls',
        pattern: /(snapshotLayerSegmentGraphByLayerIds|restoreLayerSegmentGraphSnapshot)\(/g,
        max: 2,
      },
    ],
    requiredRegexes: [
      /useTranscriptionProjectMediaController\(\{/,
      /useTranscriptionSelectionSnapshot\(\{/,
      /useTranscriptionSelectionContextController\(\{/,
      /useTranscriptionSegmentBridgeController\(\{/,
      /useTranscriptionShellController\(\{/,
      /useTranscriptionSpeakerController\(\{/,
      /useTrackEntityPersistenceController\(\{/,
      /useTrackEntityStateController\(\{/,
      /useWaveformRuntimeController\(\)/,
      /useBatchOperationController\(\{/,
      /useSpeakerActionScopeController\(\{/,
      /useTranscriptionAssistantController\(\{/,
      /useTranscriptionSegmentCreationController\(\{/,
      /useTranscriptionSegmentMutationController\(\{/,
      /useTranscriptionTimelineController\(\{/,
      /useTranscriptionTimelineInteractionController\(\{/,
      /useTranscriptionWaveformBridgeController\(\{/,
      /useTranscriptionWorkspaceLayoutController\(\{/,
      /useTrackDisplayController\(\{/,
      // Phase 9 — Timeline unit read model (CQRS) wiring must stay in ReadyWorkspace
      /useTimelineUnitViewIndex\(\{/,
      /timelineUnitsOnCurrentMedia:\s*timelineUnitViewIndex\.currentMediaUnits/,
      /timelineUnitViewIndex,\s*$/m,
    ],
    forbiddenLiterals: [
      'LayerSegmentationV2Service.createSegment(',
      'LayerSegmentationV2Service.createSegmentWithParentConstraint(',
      'LayerSegmentationV2Service.splitSegment(',
      'LayerSegmentationV2Service.mergeAdjacentSegments(',
      'LayerSegmentationV2Service.deleteSegment(',
      'LayerSegmentationV2Service.updateSegment(',
    ],
    warnAtRatio: 0.85,
  },
  hookRule('useVoiceAgent', {
    maxLines: 930,
    maxUseCallbackDecls: 27,
    maxUseMemoDecls: 0,
    maxUseEffects: 4,
  }),
  hookRule('useAiChat', {
    maxLines: 1200,
    maxUseCallbackDecls: 16,
    maxUseMemoDecls: 3,
    maxUseEffects: 4,
    requiredRegexes: [
      /export function useAiChat\(options\?: UseAiChatOptions\)/,
      /import \{ createAssistantStream \} from '\.\/useAiChat\.streamFactory';/,
      /import \{ enrichContextWithRag \} from '\.\/useAiChat\.rag';/,
      /import \{ resolveToolDecisionPipeline \} from '\.\/useAiChat\.toolDecisionPipeline';/,
      /import \{ executeConfirmedToolCall \} from '\.\/useAiChat\.confirmExecution';/,
    ],
  }),
  hookRule('useTimelineUnitViewIndex', {
    maxLines: 70,
    maxUseCallbackDecls: 0,
    maxUseMemoDecls: 1,
    maxUseEffects: 0,
  }),
  hookRule('useTranscriptionData', {
    maxLines: 600,
    maxUseCallbackDecls: 0,
    maxUseMemoDecls: 0,
    maxUseEffects: 1,
  }),
  pageControllerRule('useBatchOperationController', {
    maxLines: 130,
    maxUseCallbackDecls: 6,
    maxUseMemoDecls: 2,
    maxUseEffects: 0,
  }),
  pageControllerRule('useSpeakerActionRoutingController', {
    maxLines: 730,
    maxUseCallbackDecls: 17,
    maxUseMemoDecls: 8,
    maxUseEffects: 1,
  }),
  pageControllerRule('useSpeakerActionScopeController', {
    maxLines: 250,
    maxUseCallbackDecls: 4,
    maxUseMemoDecls: 15,
    maxUseEffects: 0,
  }),
  pageControllerRule('useTranscriptionSpeakerController', {
    maxLines: 320,
    maxUseCallbackDecls: 3,
    maxUseMemoDecls: 6,
    maxUseEffects: 0,
  }),
  pageControllerRule('useTrackDisplayController', {
    maxLines: 260,
    maxUseCallbackDecls: 6,
    maxUseMemoDecls: 8,
    maxUseEffects: 2,
    requiredRegexes: [
      /export function useTrackDisplayController\(/,
      /timelineUnitsOnCurrentMedia\?:\s*ReadonlyArray<TimelineUnitView>/,
    ],
  }),
  pageControllerRule('useTranscriptionAssistantController', {
    maxLines: 305,
    maxUseCallbackDecls: 3,
    maxUseMemoDecls: 0,
    maxUseEffects: 1,
  }),
  pageControllerRule('useTranscriptionAiController', {
    maxLines: 420,
    maxUseCallbackDecls: 8,
    maxUseMemoDecls: 6,
    maxUseEffects: 4,
    requiredRegexes: [
      /export function useTranscriptionAiController\(/,
      // ADR-004 single-caliber: controllers must consume injected TimelineUnitViewIndex directly.
      /const effectiveUnitIndex = input\.timelineUnitViewIndex;/,
      /const projectUnitsForTools = effectiveUnitIndex\.isComplete \|\| effectiveUnitIndex\.allUnits\.length > 0/,
      /recordMetric\(\{\s*id:\s*'ai\.timeline_unit_count_mismatch'/,
      /layers:\s*input\.layers/,
      /recentActions:\s*formatRecentActions\(input\.recentTimelineEditEvents\)/,
      /unitCount:\s*effectiveUnitIndex\.totalCount/,
    ],
  }),
  pageControllerRule('useTranscriptionProjectMediaController', {
    maxLines: 300,
    maxUseCallbackDecls: 8,
    maxUseMemoDecls: 1,
    maxUseEffects: 0,
  }),
  pageControllerRule('useTranscriptionSelectionContextController', {
    maxLines: 220,
    maxUseCallbackDecls: 0,
    maxUseMemoDecls: 12,
    maxUseEffects: 0,
  }),
  pageControllerRule('useTranscriptionSegmentCreationController', {
    maxLines: 170,
    maxUseCallbackDecls: 1,
    maxUseMemoDecls: 0,
    maxUseEffects: 0,
  }),
  pageControllerRule('useTranscriptionSegmentBridgeController', {
    maxLines: 220,
    maxUseCallbackDecls: 4,
    maxUseMemoDecls: 2,
    maxUseEffects: 2,
  }),
  pageControllerRule('useTranscriptionSegmentMutationController', {
    maxLines: 430,
    maxUseCallbackDecls: 8,
    maxUseMemoDecls: 2,
    maxUseEffects: 0,
    requiredRegexes: [
      /export function useTranscriptionSegmentMutationController\(/,
      /dispatchTimelineUnitMutation\(/,
      /dispatchTimelineUnitSelectionMutation\(/,
    ],
  }),
  pageControllerRule('useTranscriptionShellController', {
    maxLines: 360,
    maxUseCallbackDecls: 4,
    maxUseMemoDecls: 1,
    maxUseEffects: 7,
  }),
  pageControllerRule('useTranscriptionTimelineController', {
    maxLines: 195,
    maxUseCallbackDecls: 0,
    maxUseMemoDecls: 7,
    maxUseEffects: 0,
  }),
  pageControllerRule('useTranscriptionTimelineInteractionController', {
    maxLines: 500,
    maxUseCallbackDecls: 15,
    maxUseMemoDecls: 0,
    maxUseEffects: 0,
  }),
  pageControllerRule('useTranscriptionWorkspaceLayoutController', {
    maxLines: 470,
    maxUseCallbackDecls: 10,
    maxUseMemoDecls: 0,
    maxUseEffects: 12,
  }),
  pageControllerRule('useTranscriptionWaveformBridgeController', {
    maxLines: 560,
    maxUseCallbackDecls: 10,
    maxUseMemoDecls: 3,
    maxUseEffects: 5,
    requiredRegexes: [
      /export function useTranscriptionWaveformBridgeController\(/,
      /timelineUnitViewIndex:\s*input\.timelineUnitViewIndex/,
    ],
  }),
  pageControllerRule('useWaveformRuntimeController', {
    maxLines: 130,
    maxUseCallbackDecls: 1,
    maxUseMemoDecls: 0,
    maxUseEffects: 3,
  }),
  pageControllerRule('useWaveformSelectionController', {
    maxLines: 170,
    maxUseCallbackDecls: 0,
    maxUseMemoDecls: 7,
    maxUseEffects: 0,
    requiredRegexes: [
      /export function useWaveformSelectionController\(/,
      /timelineUnitViewIndex:\s*TimelineUnitViewIndexWithEpoch/,
    ],
  }),
  pageControllerRule('useTrackEntityStateController', {
    maxLines: 120,
    maxUseCallbackDecls: 0,
    maxUseMemoDecls: 0,
    maxUseEffects: 2,
  }),
  pageControllerRule('useTrackEntityPersistenceController', {
    maxLines: 80,
    maxUseCallbackDecls: 0,
    maxUseMemoDecls: 0,
    maxUseEffects: 1,
  }),
  {
    file: 'src/services/VoiceAgentService.ts',
    maxLines: 1250,
    requiredRegexes: [
      /export class VoiceAgentService extends BrowserEventEmitter<VoiceAgentServiceEventMap>/,
      /export function getVoiceAgentService\(\): VoiceAgentService \| null \{/,
      /export function createVoiceAgentService\(options: VoiceAgentServiceOptions = \{\}\): VoiceAgentService \{/,
    ],
  },
  {
    file: 'src/services/GlobalContextService.ts',
    maxLines: 390,
    maxUseCallbackDecls: 1,
    maxUseMemoDecls: 0,
    maxUseEffects: 2,
  },
  patternRule(/^src\/pages\/use.*Controller\.ts$/, {
    excludeFiles: [
      'src/pages/useBatchOperationController.ts',
      'src/pages/useSpeakerActionRoutingController.ts',
      'src/pages/useSpeakerActionScopeController.ts',
      'src/pages/useTrackDisplayController.ts',
      'src/pages/useTrackEntityPersistenceController.ts',
      'src/pages/useTrackEntityStateController.ts',
      'src/pages/useTranscriptionAiController.ts',
      'src/pages/useTranscriptionAssistantController.ts',
      'src/pages/useTranscriptionProjectMediaController.ts',
      'src/pages/useTranscriptionSelectionContextController.ts',
      'src/pages/useTranscriptionSegmentBridgeController.ts',
      'src/pages/useTranscriptionSegmentCreationController.ts',
      'src/pages/useTranscriptionSegmentMutationController.ts',
      'src/pages/useTranscriptionShellController.ts',
      'src/pages/useTranscriptionTimelineController.ts',
      'src/pages/useTranscriptionTimelineInteractionController.ts',
      'src/pages/useTranscriptionWaveformBridgeController.ts',
      'src/pages/useTranscriptionWorkspaceLayoutController.ts',
      'src/pages/useWaveformRuntimeController.ts',
      'src/pages/useWaveformSelectionController.ts',
    ],
    maxLines: 800,
    maxUseCallbackDecls: 20,
    maxUseMemoDecls: 15,
    maxUseEffects: 5,
    warnAtRatio: 0.85,
    requiredRegexes: [/export function use[A-Za-z0-9]+Controller\(/],
  }),
  patternRule(/^src\/hooks\/use.*\.(ts|tsx)$/, {
    excludeFiles: [
      'src/hooks/useVoiceAgent.ts',
      'src/hooks/useTranscriptionData.ts',
    ],
    excludeRegexes: [/\.test\./, /\.structure\./],
    maxLines: 1500,
    maxUseCallbackDecls: 25,
    maxUseMemoDecls: 15,
    maxUseEffects: 15,
    warnAtRatio: 0.85,
  }),
  patternRule(/^src\/services\/.*Service\.ts$/, {
    excludeFiles: [
      'src/services/VoiceAgentService.ts',
      'src/services/GlobalContextService.ts',
    ],
    maxLines: 2000,
    maxUseCallbackDecls: 0,
    maxUseMemoDecls: 0,
    maxUseEffects: 0,
    warnAtRatio: 0.85,
    forbiddenRegexes: [
      /from ['\"]react['\"]/, 
      /\buseState\(/,
      /\buseEffect\(/,
      /\buseCallback\(/,
      /\buseMemo\(/,
      /\buseRef\(/,
    ],
  }),
  patternRule(/^src\/pages\/(?!use).*\.(ts|tsx)$/, {
    excludeFiles: ['src/pages/TranscriptionPage.Orchestrator.tsx', 'src/pages/TranscriptionPage.ReadyWorkspace.tsx'],
    excludeRegexes: [/\.test\./, /\.structure\./],
    maxLines: 800,
    maxUseCallbackDecls: 8,
    maxUseMemoDecls: 8,
    maxUseEffects: 10,
    warnAtRatio: 0.85,
  }),
  {
    file: 'src/styles/foundation/dialog-shell.css',
    requiredLiterals: [
      '.dialog-card {',
      '.dialog-header {',
      '.dialog-body {',
      '.dialog-footer {',
      '.dialog-card-compact {',
    ],
  },
  {
    file: 'src/styles/foundation/panel-primitives.css',
    requiredLiterals: [
      '.panel-section {',
      '.panel-button {',
      '.panel-input {',
      '.panel-chip {',
    ],
  },
  {
    file: 'src/styles/foundation/control-primitives.css',
    requiredLiterals: [
      '.select-caret {',
      '.input {',
      '.btn {',
      '.icon-btn {',
    ],
  },
  {
    file: 'src/styles/pages/transcription-layout.css',
    requiredLiterals: [
      '.app-shell-transcription {',
      '.app-main-transcription {',
      '.transcription-screen {',
      '.transcription-workspace {',
      '.transcription-list-panel {',
      '.transcription-side-pane {',
      '.focus-mode-badge {',
    ],
  },
  {
    file: 'src/styles/pages/transcription-toolbar.css',
    requiredLiterals: [
      '.transcription-waveform {',
      '.transcription-wave-toolbar {',
      '.transcription-wave-toolbar-right {',
      '.app-left-rail-bottom-slot .transcription-wave-toolbar-right-portaled {',
      '.transcription-ai-observer-status {',
      '.transcription-ai-observer-status-bar {',
      '.transcription-ai-observer-stage-label {',
    ],
  },
  {
    file: 'src/styles/pages/transcription-timeline.css',
    requiredLiterals: [
      '.timeline-scroll {',
      '.timeline-content {',
      '.timeline-lane {',
      '.timeline-annotation {',
      '.timeline-text-item {',
      '.timeline-translation-audio-controls {',
      '.timeline-annotation-subtrack {',
      '.timeline-lane-focused {',
      '.timeline-lane-label {',
      '.lane-label-resize-handle {',
      '.lane-link-stack {',
      '.waveform-overview-bar {',
      '.timeline-lane-resize-handle {',
      '.timeline-lane-row-dragging {',
    ],
  },
  {
    file: 'src/styles/pages/ai-sidebar-shell.css',
    requiredLiterals: [
      '.transcription-hub-sidebar {',
      '.transcription-ai-panel {',
      '.transcription-ai-panel-toggle {',
      '.transcription-ai-panel-resizer {',
    ],
  },
  {
    file: 'src/styles/pages/app-shell-layout.css',
    requiredLiterals: [
      '.app-shell {',
      '.app-shell-body {',
      '.app-main {',
      '.app-side-pane {',
    ],
  },
  {
    file: 'src/styles/pages/feature-availability.css',
    requiredLiterals: [
      '.app-side-pane-feature-stack {',
      '.app-side-pane-feature-badge {',
      '.feature-availability-panel {',
      '.feature-availability-link {',
    ],
  },
  {
    file: 'src/styles/panels/shortcuts-panel.css',
    requiredLiterals: [
      '.pnl-shortcuts-panel {',
      '.shortcuts-panel-header {',
      '.shortcuts-panel-body {',
      '.shortcuts-panel-table {',
    ],
  },
  {
    file: 'src/styles/panels/ai-chat-thread.css',
    requiredLiterals: [
      '.ai-chat-message-viewport {',
      '.ai-chat-message-canvas {',
      '.ai-chat-message-surface {',
      '.ai-chat-message-actions {',
    ],
  },
  {
    file: 'src/styles/panels/left-rail-project-hub.css',
    requiredLiterals: [
      '.left-rail-project-hub-root {',
      '.left-rail-project-import-dialog {',
      '.left-rail-project-import-table {',
      '.left-rail-project-import-actions {',
    ],
  },
  {
    file: 'src/styles/panels/undo-history.css',
    requiredLiterals: [
      '.transcription-undo-chip {',
      '.transcription-undo-history {',
      '.transcription-undo-history-item {',
      '.transcription-undo-history-redo {',
    ],
  },
  {
    file: 'src/styles/global.css',
    forbiddenRegexes: [
      /^\.select-caret(?=[:\s,{])/m,
      /^\.input(?=[:\s,{])/m,
      /^\.textarea(?=[:\s,{])/m,
      /^\.btn(?=[:\s,{])/m,
      /^\.btn-ghost(?=[:\s,{])/m,
      /^\.btn-danger(?=[:\s,{])/m,
      /^\.icon-btn(?=[:\s,{])/m,
      /^\.app-shell\s*\{/m,
      /^\.app-shell-body\s*\{/m,
      /^\.app-main\s*\{/m,
      /^\.app-left-rail\s*\{/m,
      /^\.app-left-rail-group\s*\{/m,
      /^\.app-left-rail-bottom-slot\s*\{/m,
      /^\.app-side-pane\s*\{/m,
      /^\.app-side-pane-transcription\s*\{/m,
      /^\.app-shell-side-pane-collapsed\b/m,
      /^\.app-side-pane-collapsed\b/m,
      /^\.app-side-pane-collapse-toggle\b/m,
      /^\.app-side-pane-handle-cluster\b/m,
      /^\.app-side-pane-hover-zone\s*\{/m,
      /^\.app-side-pane-resizer\b/m,
      /^\.app-side-pane-header\s*\{/m,
      /^\.app-side-pane-title\s*\{/m,
      /^\.app-side-pane-subtitle\s*\{/m,
      /^\.app-side-pane-body\s*\{/m,
      /^\.app-side-pane-body-slot\s*\{/m,
      /^\.app-side-pane-empty-state\b/m,
      /^\.app-main-transcription\b/m,
      /^\.app-side-pane-feature-stack/m,
      /^\.app-side-pane-feature-nav/m,
      /^\.app-side-pane-feature-badge/m,
      /^\.app-side-pane-feature-summary/m,
      /^\.app-side-pane-feature-item/m,
      /^\.app-side-pane-feature-link/m,
      /^\.feature-availability-panel/m,
      /^\.feature-availability-badge/m,
      /^\.feature-availability-summary/m,
      /^\.feature-availability-block/m,
      /^\.feature-availability-label/m,
      /^\.feature-availability-list/m,
      /^\.feature-availability-actions/m,
      /^\.feature-availability-link/m,
    ],
  },
  {
    file: 'src/styles/pages/transcription-waveform.css',
    forbiddenRegexes: [
      /^\.dialog-overlay/m,
      /^\.dialog-card\s*\{/m,
      /^\.dialog-header\s*\{/m,
      /^\.dialog-body\s*\{/m,
      /^\.dialog-footer\s*\{/m,
      /^\.panel-organization-surface\s*\{/m,
      /^\.side-pane-action-modal/m,
      /^\.transcription-side-pane-speaker-panel/m,
      /^\.speaker-action-dialog/m,
      /^\.speaker-management-panel-card/m,
      /^\.speaker-management-dialog-actions/m,
      /^\.layer-action-dialog/m,
      /^\.layer-manager__/m,
      /^\.batch-operation/m,
      /^\.pdf-viewer-panel/m,
      /^\.transcription-screen\s*\{/m,
      /^\.app-shell-transcription\s*\{/m,
      /^\.app-shell-transcription \.app-main-transcription\s*\{/m,
      /^\.app-main-transcription \.transcription-screen\s*\{/m,
      /^\.transcription-workspace\s*\{/m,
      /^\.transcription-list-panel\s*\{/m,
      /^\.transcription-list-main\s*\{/m,
      /^\.transcription-side-pane\s*\{/m,
      /^\.transcription-side-pane::after/m,
      /^\.transcription-waveform\s*\{/m,
      /^\.transcription-wave-toolbar/m,
      /^\.transcription-toolbar-/m,
      /^\.app-left-rail-bottom-slot \.transcription-wave-toolbar-right-portaled/m,
      /^\.transcription-ai-observer-/m,
      /^\.timeline-scroll\s*\{/m,
      /^\.timeline-content\s*\{/m,
      /^\.timeline-lasso-rect\s*\{/m,
      /^\.timeline-lane\s*\{/m,
      /^\.timeline-annotation-subtrack/m,
      /^\.timeline-lane-(translation|focused|collapsed|overlap-hint|flash|header)/m,
      /^\.timeline-lane-label\s*\{/m,
      /^\.lane-label-resize-handle\s*\{/m,
      /^\.transcription-list-main-lane-header-collapsed \.timeline-lane-label/m,
      /^\.timeline-lane-resize-handle/m,
      /^\.timeline-lane-row-dragging\s*\{/m,
      /^\.timeline-lane-boundary-highlight-top::before/m,
      /^\.timeline-lane-bundle-target\s*\{/m,
      /^\.timeline-annotation/m,
      /^\.timeline-content-text-only\s*\{/m,
      /^\.timeline-lane-text-only/m,
      /^\.timeline-text-item/m,
      /^\.timeline-text-input\s*\{/m,
      /^@keyframes timeline-status-pulse/m,
      /^\.timeline-translation-audio-/m,
      /^\.timeline-empty-/m,
      /^\.timeline-resize-tooltip\s*\{/m,
      /^\.waveform-area-resizing\s*\{/m,
      /^\.transcription-waveform-resize-handle\s*\{/m,
      /^\.ai-chat-message-viewport/m,
      /^\.ai-chat-message-canvas/m,
      /^\.ai-chat-message-surface/m,
      /^\.ai-chat-message-actions/m,
      /^\.ai-chat-message-action-btn/m,
      /^\.ai-citation-marker/m,
      /^\.transcription-analysis-panel/m,
      /^\.transcription-ai-stats-panel/m,
      /^\.left-rail-project-hub-root/m,
      /^\.left-rail-project-import-dialog/m,
      /^\.left-rail-project-import-table/m,
      /^\.transcription-undo-chip/m,
      /^\.transcription-undo-history/m,
    ],
  },
  {
    file: 'src/styles/ai-hub.css',
    forbiddenRegexes: [
      /^\.dialog-card\s*\{/m,
      /^\.note-panel/m,
      /^\.note-popover/m,
      /^\.ai-chat-replay-panel/m,
      /^\.ai-chat-prompt-lab-panel-content/m,
      /^\.ai-chat-prompt-lab-template-row/m,
      /^\.ai-chat-prompt-lab-item-title/m,
      /^\.ai-chat-prompt-lab-input/m,
      /^\.ai-chat-prompt-lab-textarea/m,
      /^\.ai-chat-prompt-lab-token-row/m,
      /^\.ai-chat-prompt-lab-action-row/m,
      /^\.transcription-hub-sidebar(\s|\{|-)/m,
      /^\.transcription-ai-tab-badge/m,
      /^\.transcription-hub-assistant-panel\s*\{/m,
      /^\.transcription-ai-panel\s*\{/m,
      /^\.transcription-ai-panel::before/m,
      /^\.transcription-ai-panel-toggle\s*\{/m,
      /^\.transcription-ai-panel-resizer\s*\{/m,
      /^\.transcription-ai-panel-handle-cluster\s*\{/m,
      /^\.transcription-undo-chip/m,
      /^\.transcription-undo-chip-label/m,
    ],
  },
  patternRule(/^src\/pages\/use.*\.(ts|tsx)$/, {
    excludeRegexes: [/Controller\.ts$/, /\.test\./, /\.structure\./],
    maxLines: 300,
    maxUseCallbackDecls: 6,
    maxUseMemoDecls: 6,
    maxUseEffects: 4,
    warnAtRatio: 0.85,
    requiredRegexes: [/export function use[A-Za-z0-9]+\(/],
  }),
  patternRule(/^src\/components\/.*\.(ts|tsx)$/, {
    excludeRegexes: [/\.test\./, /\.structure\./],
    maxLines: 2000,
    maxUseCallbackDecls: 25,
    maxUseMemoDecls: 25,
    maxUseEffects: 20,
    warnAtRatio: 0.85,
  }),
  patternRule(/^src\/contexts\/.*\.(ts|tsx)$/, {
    excludeRegexes: [/\.test\./, /\.structure\./],
    maxLines: 800,
    maxUseCallbackDecls: 10,
    maxUseMemoDecls: 10,
    maxUseEffects: 10,
    warnAtRatio: 0.85,
  }),

  // ── ADR-003 Phase 16: forbid resurrecting removed legacy mirror modules | DB cutover guard ──
  patternRule(/^src\/services\/(?!.*\.test\.).*\.ts$/, {
    excludeFiles: ['src/services/LayerUnitSegmentWritePrimitives.ts'],
    forbiddenRegexes: [
      /\bLegacyMirrorService\b/,
      /LayerUnitSegmentMirrorPrimitives/,
    ],
  }),

  // ── ADR-006 M18: forbid resurrecting Dexie `utterances` store (allowlist: engine upgrade, M18 migration) ──
  patternRule(/^src\/.*\.(ts|tsx)$/, {
    excludeRegexes: [/\.test\.(ts|tsx)$/, /\.structure\.(ts|tsx)$/],
    excludeFiles: [
      'src/db/engine.ts',
      'src/db/migrations/m18LinguisticUtteranceCutover.ts',
    ],
    forbiddenRegexes: [
      /\bdb\.utterances\b/,
      /\bdexie\.utterances\b/,
      /\bcollections\.utterances\b/,
      /collections\[\s*['"]utterances['"]\s*\]/,
    ],
  }),

  // ── ADR-006 M18: subgraph must not query legacy `utteranceId` index (allowlist: engine historical schema strings only if needed) ──
  patternRule(/^src\/.*\.(ts|tsx)$/, {
    excludeRegexes: [/\.test\.(ts|tsx)$/, /\.structure\.(ts|tsx)$/],
    excludeFiles: [
      'src/db/engine.ts',
      'src/db/migrations/m18LinguisticUtteranceCutover.ts',
    ],
    forbiddenRegexes: [
      /utterance_tokens\.where\(\s*['"]utteranceId['"]/,
      /utterance_morphemes\.where\(\s*['"]utteranceId['"]/,
      /\.utterance_tokens\.where\(\s*['"]utteranceId['"]/,
      /\.utterance_morphemes\.where\(\s*['"]utteranceId['"]/,
    ],
  }),

  // ── M3 依赖方向守卫 | M3 dependency direction guard ──

  // 应用服务层禁止反向依赖页面层或组件层 | App service layer must NOT import pages or components
  patternRule(/^src\/app\/.*\.(ts|tsx)$/, {
    excludeRegexes: [/\.test\./],
    maxLines: 800,
    forbiddenRegexes: [
      /from ['"]\.\.\/pages\//,
      /from ['"]\.\.\/components\//,
    ],
  }),

  // 应用服务层入口契约 | App service barrel contract
  {
    file: 'src/app/index.ts',
    requiredLiterals: [
      'TranscriptionAppService',
      'AiAppService',
      'LanguageAssetsAppService',
      'contracts',
    ],
  },

  // 冻结页面层直连 db 的文件数（基线 46，仅允许下降不允许上涨） | Freeze page→db import file count (baseline 46, must not increase)
  patternRule(/^src\/pages\/(?!.*\.test\.).*\.(ts|tsx)$/, {
    maxRegexMatchCounts: [
      {
        label: 'page→db direct imports (M3 baseline 46, frozen — new files must be 0)',
        pattern: /^import .* from ['"]\.\.\/db/gm,
        max: 0,
      },
    ],
    excludeFiles: [
      // ── 以下为 M3 基线冻结时已存在直连 db 的文件（已豁免） | Existing files at M3 baseline (exempted) ──
      'src/pages/languageMetadataWorkspace.customFieldController.ts',
      'src/pages/languageMetadataWorkspace.shared.ts',
      'src/pages/LanguageMetadataWorkspaceCustomFieldDefinitionCard.tsx',
      'src/pages/LanguageMetadataWorkspaceCustomFieldValueField.tsx',
      'src/pages/LexiconPage.tsx',
      'src/pages/OrchestratorWaveformContent.tsx',
      'src/pages/OrthographyBridgeWorkspacePage.tsx',
      'src/pages/orthographyManager.shared.ts',
      'src/pages/OrthographyManagerPage.tsx',
      'src/pages/OrthographyManagerPanel.tsx',
      'src/pages/transcriptionReadyWorkspaceOrchestratorInput.ts',
      'src/pages/transcriptionAiController.types.ts',
      'src/pages/transcriptionAiToolRiskCheck.ts',
      'src/pages/transcriptionAssistantContextValue.ts',
      'src/pages/transcriptionAssistantController.types.ts',
      'src/pages/TranscriptionPage.BatchOps.tsx',
      'src/pages/TranscriptionPage.citationJump.ts',
      'src/pages/TranscriptionPage.runtimeContracts.ts',
      'src/pages/TranscriptionPage.runtimeProps.ts',
      'src/pages/transcriptionSectionViewModelTypes.ts',
      'src/pages/transcriptionSegmentCreationActions.ts',
      'src/pages/transcriptionSegmentRouting.ts',
      'src/pages/transcriptionSelectionSnapshot.ts',
      'src/pages/transcriptionTimelineTopProps.ts',
      'src/pages/transcriptionWaveformBridge.types.ts',
      'src/pages/timelineUnitViewUtteranceHelpers.ts',
      'src/pages/useBatchOperationController.ts',
      'src/pages/useSpeakerActionRoutingController.ts',
      'src/pages/useSpeakerActionScopeController.ts',
      'src/pages/useTrackDisplayController.ts',
      'src/pages/useTranscriptionAiController.segmentTargets.ts',
      'src/pages/useTranscriptionAiController.ts',
      'src/pages/useTranscriptionAnalysisRuntimeProps.ts',
      'src/pages/useTranscriptionAssistantController.ts',
      'src/pages/useTranscriptionAssistantRuntimeProps.ts',
      'src/pages/useTranscriptionDisplayStyleControl.ts',
      'src/pages/useTranscriptionProjectMediaController.ts',
      'src/pages/useTranscriptionRuntimeProps.ts',
      'src/pages/useTranscriptionSegmentBatchMerge.ts',
      'src/pages/useTranscriptionSegmentBridgeController.ts',
      'src/pages/useTranscriptionSegmentMutationController.ts',
      'src/pages/useTranscriptionSelectionContextController.ts',
      'src/pages/useTranscriptionShellController.ts',
      'src/pages/useTranscriptionSpeakerController.ts',
      'src/pages/useTranscriptionTimelineController.ts',
      'src/pages/useTranscriptionWorkspaceLayoutController.ts',
      'src/pages/useWaveformSelectionController.ts',
      'src/pages/voiceDictationRuntime.ts',
    ],
  }),

  // 冻结页面层直连 services 的文件数（基线 34，仅允许下降不允许上涨） | Freeze page→services import file count (baseline 34, must not increase)
  patternRule(/^src\/pages\/(?!.*\.test\.).*\.(ts|tsx)$/, {
    maxRegexMatchCounts: [
      {
        label: 'page→services direct imports (M3 baseline 34, frozen — new files must be 0)',
        pattern: /^import .* from ['"]\.\.\/services\//gm,
        max: 0,
      },
    ],
    excludeFiles: [
      // ── 以下为 M3 基线冻结时已存在直连 services 的文件（已豁免） | Existing files at M3 baseline (exempted) ──
      'src/pages/languageMetadataWorkspace.customFieldController.ts',
      'src/pages/languageMetadataWorkspace.shared.ts',
      'src/pages/LanguageMetadataWorkspaceCustomFieldDefinitionCard.tsx',
      'src/pages/LanguageMetadataWorkspaceCustomFieldValueField.tsx',
      'src/pages/LanguageMetadataWorkspaceDetailColumn.tsx',
      'src/pages/LanguageMetadataWorkspacePage.tsx',
      'src/pages/LexiconPage.tsx',
      'src/pages/OrthographyBridgeWorkspacePage.tsx',
      'src/pages/orthographyBrowse.shared.ts',
      'src/pages/OrthographyManagerPage.tsx',
      'src/pages/OrthographyManagerPanel.tsx',
      'src/pages/transcriptionAiController.types.ts',
      'src/pages/transcriptionAssistantController.types.ts',
      'src/pages/TranscriptionPage.AssistantBridge.tsx',
      'src/pages/TranscriptionPage.runtimeContracts.ts',
      'src/pages/TranscriptionPage.runtimeProps.ts',
      'src/pages/transcriptionSegmentCreationActions.ts',
      'src/pages/useSpeakerActionRoutingController.ts',
      'src/pages/useTrackEntityPersistenceController.ts',
      'src/pages/useTrackEntityStateController.ts',
      'src/pages/useTranscriptionAcousticPanelState.ts',
      'src/pages/useTranscriptionAiAcousticRuntime.ts',
      'src/pages/useTranscriptionAiController.ts',
      'src/pages/useTranscriptionAssistantController.ts',
      'src/pages/useTranscriptionAssistantRuntimeProps.ts',
      'src/pages/useTranscriptionDisplayStyleControl.ts',
      'src/pages/useTranscriptionProjectMediaController.ts',
      'src/pages/useTranscriptionRuntimeProps.ts',
      'src/pages/useTranscriptionSegmentBatchMerge.ts',
      'src/pages/useTranscriptionSegmentBridgeController.ts',
      'src/pages/useTranscriptionSegmentMutationController.ts',
      'src/pages/useTranscriptionShellController.ts',
      'src/pages/useTranscriptionTimelineInteractionController.ts',
      'src/pages/useWaveformAcousticOverlay.ts',
      'src/pages/voiceDictationRuntime.ts',
    ],
  }),
];
